export const scoringConfig = {
  initialAbility: 500,
  minScore: 10,
  maxScore: 990,
  domainMinScore: 1,
  domainMaxScore: 99,
  displayStep: 5,
  logisticScale: 180,
  baseK: 95,
  easyCorrectDampening: 0.45,
  perfectStreakDampeningFloor: 1,
  hardWrongDampening: 0.55,
  minStandardError: 28,
  initialStandardError: 180,
  earlyUncertaintyMultiplier: 1.85,
  midUncertaintyMultiplier: 1.2,
  stableAnswerThreshold: 100,
  highAccuracyThreshold: 50,
  overallAbilityBlend: 0.35,
  domainAbilityBlend: 0.4,
  axisAbilityBlend: 0.25,
  firstQuestionTargetProbability: 0.7,
  lowCumulativeRateThreshold: 0.7,
  lowRateTargetBand: { min: 0.7, max: 0.9 },
  highRateTargetBand: { min: 0.5, max: 0.7 },
  perfectRateTargetBand: { min: 0.2, max: 0.34 },
  maxSelectionAbilityInflation: 155,
  difficultyRampStart: 500,
  difficultyRampEnd: 900,
  difficultyRampQuestions: 20,
  surpriseFloorAtPerfect: 0.62,
  bandRelaxationStep: 0.08,
  maxBandRelaxationSteps: 4,
  candidatePoolSize: 5,
  selectionWeights: {
    inBand: 3,
    nearBand: 1.5,
    quality: 2,
    coverage: 4,
    exposureBalance: 1.5,
    avoidSimilar: 0.15
  },
  feedbackWeightDivisor: 990
} as const;
