"use client";
import { scoreCeiling } from "@/src/lib/science/versions";
import { useEffect,useState } from "react";
import { AppButton } from "@/components/ui/AppButton";
import { AppCard } from "@/components/ui/AppCard";
import { domains } from "@/src/lib/data/taxonomy";
import { scienceApi } from "@/src/lib/science/client";
import type { AccountData,Preferences,ScienceProfile } from "@/src/lib/science/account";
import { ScienceMap } from "./ScienceMap";

const badgeNames:Record<string,string>={"ten-domains":"10分野を受験","first-full":"初めての本試験完走","weekly-three":"3週の科学チャレンジャー","lab-explorer":"ラボの探究者","improvement":"良問の育て手"};
const date=(value:string)=>new Date(value).toLocaleString("ja-JP",{timeZone:"Asia/Tokyo"});
export function AccountClient(){
  const [data,setData]=useState<AccountData|null>(null);const [profile,setProfile]=useState<ScienceProfile|null>(null);const [preferences,setPreferences]=useState<Preferences>({science:false,weekly:false,domain_opening:false});const [page,setPage]=useState(0);const [error,setError]=useState("");const [note,setNote]=useState("");const [busy,setBusy]=useState(false);
  async function load(p:number){setBusy(true);setError("");try{const next=await scienceApi<AccountData>("account",{page:p});setData(next);setProfile(next.profile);setPreferences(next.preferences);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  useEffect(()=>{void load(page);},[page]);
  return <main className="page-container max-w-5xl py-8"><h1 className="text-3xl font-black">マイページ</h1><p className="mt-3 text-[var(--color-muted)]">現在の推定、今回の記録、自己ベストを分けて残しています。</p>
    {error&&<AppCard className="mt-5"><p role="alert">{error}</p><AppButton className="mt-3" onClick={()=>void load(page)} disabled={busy}>再読み込み</AppButton></AppCard>}
    {!data&&!error&&<p role="status" className="mt-8">保存済みの記録を読み込んでいます…</p>}
    {data&&<><div className="mt-5 flex flex-wrap gap-3"><AppButton href="/training" variant="secondary">5問ずつ復習</AppButton><AppButton href="/lab" variant="ghost">作問ノートへ</AppButton></div>
      {!data.signedIn&&<AppCard className="mt-6"><h2 className="text-xl font-black">この端末の受験記録</h2><p className="mt-3 leading-7">無料登録すると、この記録をアカウントへ引き継ぎ、別の端末でも再開・復習できます。</p><AppButton href="/signup?next=%2Fmypage" className="mt-4">メールで無料登録</AppButton></AppCard>}
      <AppCard className="mt-6"><h2 className="text-2xl font-black">受験履歴・中断再開</h2>{data.history.length===0?<p className="mt-4">この版の受験記録はまだありません。</p>:<ul className="mt-4 divide-y">{data.history.map((a)=><li key={a.id} className="flex flex-wrap items-center justify-between gap-3 py-4"><div><p className="font-bold">{a.definition.label}</p><p className="mt-1 text-sm">{a.ordinal}/{a.definition.count}問 · {a.state==="completed"?"完了":a.state==="active"?"中断中":"途中で終了"}{a.completed_at&&` · ${date(a.completed_at)}`}</p></div>{a.state!=="abandoned"&&<AppButton href={a.state==="active"?`/exam?attempt=${a.id}`:`/result?attempt=${a.id}`} variant="secondary">{a.state==="active"?"再開する":"結果・復習・共有"}</AppButton>}</li>)}</ul>}
        <div className="mt-4 flex flex-wrap gap-3"><AppButton disabled={page===0||busy} onClick={()=>setPage(p=>p-1)} variant="ghost">前の20件</AppButton><span className="self-center text-sm">{page+1}ページ · 全{data.historyTotal}件</span><AppButton disabled={(page+1)*20>=Math.max(data.historyTotal,data.legacyTotal)||busy} onClick={()=>setPage(p=>p+1)} variant="ghost">次の20件</AppButton><AppButton href="/exam">新しい受験へ</AppButton></div>
      </AppCard>
      <AppCard className="mt-6"><h2 className="text-2xl font-black">現在の推定</h2><p className="mt-3 leading-7">大分野ごとの直近100件の適格回答を使い、新しい回答ほど重く見ます。30回答前の重みは半分です。時間が過ぎただけで点数は下がりません。</p>{data.current.total!==null&&<p className="mt-4 text-3xl font-black">{data.current.total}/{scoreCeiling(data.current.version)}点 <span className="text-sm font-normal">参考スコア</span></p>}<ScienceMap result={data.current}/><ul className="mt-4 grid gap-1 text-xs text-[var(--color-muted)]">{domains.filter(d=>data.current.domains[d].lastAnsweredAt).map(d=><li key={d}>{d}の最終回答：{date(data.current.domains[d].lastAnsweredAt!)}</li>)}</ul><p className="mt-3 text-xs leading-6 text-[var(--color-muted)]">復習・ラボ・自作問題は含みません。分野別の幅はモデルに基づく区間で、実測での精度検証を進めています。</p></AppCard>
      <AppCard className="mt-6"><h2 className="text-2xl font-black">自己ベスト</h2><p className="mt-2 text-sm text-[var(--color-muted)]">同じ種類・問題数・採点版の受験どうしで比較。現在の実力とは区別しています。</p>{data.recalculationPending>0&&<p role="status" className="mt-4 rounded-xl bg-amber-50 p-4 text-sm leading-7">訂正を反映中の記録が{data.recalculationPending}件あります。再計算が終わるまで自己ベストの比較から一時的に外れます。過去の履歴を開くと、その記録を更新できます。</p>}{data.bests.length===0?<p className="mt-4">{data.recalculationPending>0?"再計算後の記録が揃うと表示されます。":"受験を完了すると表示されます。"}</p>:<ul className="mt-4 divide-y">{data.bests.map(b=><li key={b.id} className="flex items-center justify-between gap-3 py-3"><span>{b.result.definition.label} · {b.result.total??(b.domain?b.result.domains[b.domain as keyof typeof b.result.domains]?.score:"—")}点</span><AppButton href={`/result?attempt=${b.id}`} variant="ghost">記録を見る</AppButton></li>)}</ul>}</AppCard>
      {data.badges.length>0&&<AppCard className="mt-6"><h2 className="text-2xl font-black">実績バッジ</h2><ul className="mt-4 flex flex-wrap gap-3">{data.badges.map(b=><li className="rounded-xl bg-[var(--color-primary-50)] p-3" key={b.code}>{badgeNames[b.code]??b.code}</li>)}</ul></AppCard>}
      {data.signedIn&&<AppCard className="mt-6"><h2 className="text-2xl font-black">旧版の保存結果</h2><p className="mt-3 text-sm leading-7">以前の尺度のまま保存しています。新版の点数へ換算・合算していません。旧版の途中受験は改装後の出題とはつながらないため、新しい受験からお楽しみください。</p>{data.legacy.length===0?<p className="mt-4">このページに旧版の保存結果はありません。</p>:<ul className="mt-4 divide-y">{data.legacy.map(l=><li key={l.id} className="py-3">{date(l.created_at)} · 旧版 {l.score}点 · {l.answer_count}問</li>)}</ul>}</AppCard>}
      {profile&&<AppCard className="mt-6"><h2 className="text-2xl font-black">プロフィールと公開設定</h2><form className="mt-5 grid gap-4" onSubmit={async(e)=>{e.preventDefault();setBusy(true);setError("");try{await scienceApi("profile",{nickname:profile.nickname,bio:profile.bio,interests:profile.interests,isPublic:profile.is_public,rankingOptIn:profile.ranking_opt_in});setNote("プロフィールを保存しました。");}catch(issue){setError((issue as Error).message);}finally{setBusy(false);}}}>
        <label>ニックネーム<input value={profile.nickname} onChange={(e)=>setProfile({...profile,nickname:e.target.value})} maxLength={30} required className="mt-2 block min-h-12 w-full rounded-xl border p-3"/></label><label>短い自己紹介<textarea value={profile.bio} onChange={(e)=>setProfile({...profile,bio:e.target.value})} maxLength={160} className="mt-2 block min-h-24 w-full rounded-xl border p-3"/></label>
        <fieldset><legend>興味のある分野</legend><div className="mt-3 grid grid-cols-2 gap-3">{domains.map(d=><label key={d} className="flex items-center gap-2"><input type="checkbox" checked={profile.interests.includes(d)} onChange={(e)=>setProfile({...profile,interests:e.target.checked?[...profile.interests,d]:profile.interests.filter(v=>v!==d)})}/>{d}</label>)}</div></fieldset>
        <label className="flex items-start gap-3"><input type="checkbox" checked={profile.is_public} onChange={(e)=>setProfile({...profile,is_public:e.target.checked})} className="mt-1"/><span>ニックネーム・自己紹介・興味分野・自分で共有した記録の入口を公開する</span></label>
        <label className="flex items-start gap-3"><input type="checkbox" checked={profile.ranking_opt_in} onChange={(e)=>setProfile({...profile,ranking_opt_in:e.target.checked})} className="mt-1"/><span>ニックネームと対象の受験成績をランキングに掲載する</span></label><AppButton type="submit" disabled={busy}>設定を保存</AppButton>{profile.is_public&&<AppButton href={`/u/${profile.public_id}`} variant="ghost">公開プロフィールを見る</AppButton>}
      </form></AppCard>}
      {data.signedIn&&<AppCard className="mt-6"><h2 className="text-2xl font-black">メールの配信設定</h2><p className="mt-3 leading-7">科学の案内は初回2通、今週の10問は週1回。配信停止後も受験・保存の利用権はそのままです。</p><form className="mt-4 grid gap-4" onSubmit={async(e)=>{e.preventDefault();setBusy(true);setError("");try{await scienceApi("preferences",{preferences,operationId:crypto.randomUUID()});setNote("配信設定を保存しました。");}catch(issue){setError((issue as Error).message);}finally{setBusy(false);}}}>{([["science","科学の案内・勉強会・専門家紹介・理系とーくバー"],["weekly","今週の10問（週1回）"],["domain_opening","希望分野の公開通知"]] as const).map(([key,label])=><label key={key} className="flex items-start gap-3"><input type="checkbox" checked={preferences[key]} onChange={(e)=>setPreferences({...preferences,[key]:e.target.checked})} className="mt-1"/>{label}</label>)}<AppButton type="submit" disabled={busy}>配信設定を保存</AppButton></form></AppCard>}
      <p role="status" className="mt-4">{note}</p>
    </>}
  </main>;
}
