import { q } from "../lib/batch50-helpers.mjs";

export const humanitiesGap = [
  // L100 ×2
  q({
    domain: "人文社会科学",
    subdomain: "経済学",
    difficulty_initial: 100,
    cognitive_type: "用語・定義",
    question_text: "お金が物の交換や価値の尺度として機能することを、経済学では一般に何というか。",
    choices: ["貨幣の機能", "関税の徴収", "株価の変動", "人口の増加"],
    correct_choice_index: 0,
    short_explanation: "貨幣は交換手段・価値尺度・価値貯蔵手段などの機能を持つ。",
    detailed_explanation: "物々交換の不便を解消し、価格表示や支払いに用いられる。関税・株価・人口は貨幣の定義的機能ではない。",
    learning_objective: "貨幣の基本的機能を説明できる",
    common_misconception: "お金は単なる紙切れで特別な役割がないと考える",
    distractor_rationales: ["正解。交換・尺度・貯蔵などの機能。", "不正解。国境を越える取引の課税。", "不正解。金融市場の価格指標。", "不正解。人口動態の指標。"],
    basic_terms: "貨幣：交換手段・価値尺度としてのお金、物々交換：直接の物の交換"
  }),
  q({
    domain: "人文社会科学",
    subdomain: "政治学",
    difficulty_initial: 100,
    cognitive_type: "原理・因果",
    question_text: "民主主義国家で国民が代表者を選ぶ行為の目的として最も適切なものはどれか。",
    choices: ["国民の意思を政治に反映させる", "裁判官を直接任命する", "法律を解釈する", "税金を徴収する"],
    correct_choice_index: 0,
    short_explanation: "選挙は国民の政治参加の主要な手段であり、代表者選出を通じて意思を反映する。",
    detailed_explanation: "裁判は司法、法律解釈も司法の役割。徴税は行政の機能。選挙の核心は代表制による意思反映。",
    learning_objective: "選挙の基本的役割を説明できる",
    common_misconception: "選挙は形式的な儀式に過ぎないと考える",
    distractor_rationales: ["正解。代表制による意思反映。", "不正解。裁判官任命は別の手続。", "不正解。法律解釈は司法権。", "不正解。徴税は行政の機能。"],
    basic_terms: "選挙：代表者を選ぶ制度、代表制：選ばれた者が国民の意思を代弁する仕組み"
  }),
  // L200 ×3
  q({
    domain: "人文社会科学",
    subdomain: "歴史",
    difficulty_initial: 200,
    cognitive_type: "原理・因果",
    question_text: "江戸時代の日本が鎖国政策をとった主な目的として最も適切なものはどれか。",
    choices: ["キリスト教の浸透と外国勢力の影響を制限する", "海外貿易を拡大する", "全国を即座に近代化する", "武士階級を廃止する"],
    correct_choice_index: 0,
    short_explanation: "鎖国はキリスト教伝播の抑制と幕府支配の安定化が主目的とされる。",
    detailed_explanation: "長崎など限定港での貿易は続いた。近代化や武士廃止は明治以降の政策。",
    learning_objective: "鎖国政策の基本的背景を説明できる",
    common_misconception: "鎖国は完全な対外断絶だったと誤解する",
    distractor_rationales: ["正解。宗教・政治支配の安定化。", "不正解。貿易は限定され拡大ではない。", "不正解。近代化は明治維新以降。", "不正解。武士廃止は明治時代。"],
    basic_terms: "鎖国：対外交流を制限する政策、幕府：江戸時代の武家政権"
  }),
  q({
    domain: "人文社会科学",
    subdomain: "地理",
    difficulty_initial: 200,
    cognitive_type: "基本的な適用",
    question_text: "同じ緯度帯でも標高が高い場所ほど気温が低くなる主な理由はどれか。",
    choices: ["標高が上がるほど大気が薄くなり熱を保持しにくいから", "緯度が自動的に変わるから", "海から遠いから", "人口が少ないから"],
    correct_choice_index: 0,
    short_explanation: "標高上昇に伴い気圧・気温が低下する（気温逓減率）。",
    detailed_explanation: "高山は低緯度でも寒冷化する。緯度・距海・人口は直接の物理原因ではない。",
    learning_objective: "標高と気温の関係を説明できる",
    common_misconception: "緯度だけで気温が決まると考える",
    distractor_rationales: ["正解。大気の薄さによる冷却。", "不正解。緯度は位置で決まる。", "不正解。距海は別要因。", "不正解。人口と気温は無関係。"],
    basic_terms: "標高：海水面からの高さ、気温逓減率：高度上昇に伴う気温低下率"
  }),
  q({
    domain: "人文社会科学",
    subdomain: "法学",
    difficulty_initial: 200,
    cognitive_type: "比較・分類",
    question_text: "私人間の財産や契約の紛争を扱う法律分野として正しいものはどれか。",
    choices: ["民法", "刑法", "国際法", "憲法"],
    correct_choice_index: 0,
    short_explanation: "民法は私人間の権利義務関係を規律する基本法である。",
    detailed_explanation: "刑法は犯罪と刑罰、国際法は国家間、憲法は国家の基本秩序を定める。",
    learning_objective: "主要な法律分野の対象を区別できる",
    common_misconception: "すべての紛争が刑法で解決されると考える",
    distractor_rationales: ["正解。私人間関係の基本法。", "不正解。犯罪と刑罰。", "不正解。国家間の法。", "不正解。国家基本法。"],
    basic_terms: "民法：私人間の権利義務、刑法：犯罪と刑罰"
  }),
  // L300 ×5
  q({
    domain: "人文社会科学",
    subdomain: "心理学",
    difficulty_initial: 300,
    cognitive_type: "用語・定義",
    question_text: "フロイトの精神分析において、意識の下にあり直接意識できないが催眠などで想起可能な領域を何というか。",
    choices: ["前意識", "無意識", "超意識", "集合的無意識"],
    correct_choice_index: 0,
    short_explanation: "前意識は意識と無意識の中間で、努力により意識化できる内容を含む。",
    detailed_explanation: "無意識は抑圧され直接アクセス困難。超意識はフロイト用語ではない。集合的無意識はユングの概念。",
    learning_objective: "フロイトの意識構造の三層を区別できる",
    common_misconception: "前意識と無意識を同一視する",
    distractor_rationales: ["正解。意識化可能な中間領域。", "不正解。抑圧され直接アクセス困難。", "不正解。フロイトの標準用語ではない。", "不正解。ユングの概念。"],
    basic_terms: "前意識：意識化可能な潜在内容、無意識：抑圧された心理内容"
  }),
  q({
    domain: "人文社会科学",
    subdomain: "社会学",
    difficulty_initial: 300,
    cognitive_type: "原理・因果",
    question_text: "デュルケームが「社会的事実」として強調した性質として最も適切なものはどれか。",
    choices: ["個人の心理状態と完全に同一である", "個人を超えて存在し、個人に外的に作用する", "常に個人の自由意志のみで説明できる", "自然科学の法則とは無関係である"],
    correct_choice_index: 1,
    short_explanation: "社会的事実は個人を超えた実在であり、規範・制度などが個人に制約を与える。",
    detailed_explanation: "デュルケームは社会学の対象を個人心理と区別し、社会的事実の実在性を主張した。",
    learning_objective: "社会的事実の基本的特徴を説明できる",
    common_misconception: "社会現象はすべて個人心理の集計だと考える",
    distractor_rationales: ["不正解。個人心理とは区別される。", "正解。個人を超えた実在と外的強制。", "不正解。社会的制約が存在する。", "不正解。社会事実にも法則性を求めた。"],
    basic_terms: "社会的事実：個人を超えた社会的実在、デュルケーム：フランスの社会学者"
  }),
  q({
    domain: "人文社会科学",
    subdomain: "哲学",
    difficulty_initial: 300,
    cognitive_type: "基本的な適用",
    question_text: "ソクラテスが「無知の知」として示した態度の意味として最も適切なものはどれか。",
    choices: ["何も知らないことを誇る", "自分が真の知識を持たないことを自覚する", "知識は不要だと主張する", "他人の無知を嘲笑する"],
    correct_choice_index: 1,
    short_explanation: "無知の知は、自己の無知を認めることが真の知の出発点であるという姿勢。",
    detailed_explanation: "ソクラテスは神託を契機に、賢者と自称する者ほど無知であることを対話で示した。",
    learning_objective: "ソクラテスの無知の知の意味を説明できる",
    common_misconception: "無知の知は単なる謙遜表現だと考える",
    distractor_rationales: ["不正解。無知を誇るのではない。", "正解。自己の無知の自覚。", "不正解。知の否定ではない。", "不正解。他者批判ではない。"],
    basic_terms: "無知の知：自己の無知を知ること、ソクラテス：古代ギリシアの哲学者"
  }),
  q({
    domain: "人文社会科学",
    subdomain: "経済学",
    difficulty_initial: 300,
    cognitive_type: "比較・分類",
    question_text: "GDP（国内総生産）が測定するものとして最も適切なものはどれか。",
    choices: ["一国の政府支出のみ", "一定期間に国内で生産された付加価値の総額", "国民の貯蓄額の合計", "輸入品の総額"],
    correct_choice_index: 1,
    short_explanation: "GDPは国内で生産された最終財・サービスの市場価値の合計（付加価値の総計）。",
    detailed_explanation: "政府支出はGDPの構成要素の一つ。貯蓄・輸入はGDPの定義そのものではない。",
    learning_objective: "GDPの基本的定義を説明できる",
    common_misconception: "GDPは政府の支出額だと誤解する",
    distractor_rationales: ["不正解。支出の一部に過ぎない。", "正解。国内生産の付加価値総額。", "不正解。貯蓄は別指標。", "不正解。輸入はGDP算出で控除される。"],
    basic_terms: "GDP：Gross Domestic Product（国内総生産）、付加価値：生産過程で新たに加わった価値"
  }),
  q({
    domain: "人文社会科学",
    subdomain: "統計学",
    difficulty_initial: 300,
    cognitive_type: "誤解・境界",
    question_text: "データのばらつきを示す指標として「標準偏差」の意味として最も適切なものはどれか。",
    choices: ["データの最大値と最小値の差", "平均からのずれの大きさの代表的尺度", "データの個数", "最も頻繁に現れる値"],
    correct_choice_index: 1,
    short_explanation: "標準偏差は各データと平均の差の二乗平均の平方根で、ばらつきを表す。",
    detailed_explanation: "最大最小差はレンジ。個数はn。最頻値はモード。",
    learning_objective: "標準偏差の意味を説明できる",
    common_misconception: "標準偏差とレンジを混同する",
    distractor_rationales: ["不正解。レンジ（範囲）の定義。", "正解。平均からの散らばり。", "不正解。サンプルサイズ。", "不正解。モードの定義。"],
    basic_terms: "標準偏差：ばらつきの指標、平均：データの中心傾向"
  }),
  // L400 ×5
  q({
    domain: "人文社会科学",
    subdomain: "政治学",
    difficulty_initial: 400,
    cognitive_type: "用語・定義",
    question_text: "複数の政党が競合し、政権交代が起こりうる政治体制の特徴として最も適切なものはどれか。",
    choices: ["一党独裁が恒常的である", "複数政党制と競争的選挙が機能する", "世襲君主がすべてを決定する", "軍事政権が永続する"],
    correct_choice_index: 1,
    short_explanation: "複数政党制では複数の政党が選挙で政権を争い、交代が可能となる。",
    detailed_explanation: "一党独裁・世襲君主・軍事政権は複数政党制の特徴とは対照的。",
    learning_objective: "複数政党制の基本的特徴を説明できる",
    common_misconception: "民主主義は必ず二大政党制だと考える",
    distractor_rationales: ["不正解。一党支配は複数政党制の対極。", "正解。政党競争と政権交代の可能性。", "不正解。君主制の特徴。", "不正解。軍事政権の特徴。"],
    basic_terms: "複数政党制：複数政党が政治を担う制度、政権交代：執政党の入れ替わり"
  }),
  q({
    domain: "人文社会科学",
    subdomain: "歴史",
    difficulty_initial: 400,
    cognitive_type: "原理・因果",
    question_text: "産業革命がまずイギリスで起こった要因の組み合わせとして最も適切なものはどれか。",
    choices: ["石炭・鉄鉱石の資源、資本蓄積、市場の拡大", "完全な鎖国と農業のみの経済", "奴隷制の廃止のみ", "印刷技術の発明のみ"],
    correct_choice_index: 0,
    short_explanation: "資源、資本、労働力、市場、技術革新が複合的に産業革命を促進した。",
    detailed_explanation: "鎖国はイギリスに当てはまらない。奴隷制廃止・印刷術は単独の決定要因ではない。",
    learning_objective: "産業革命発生の主要要因を説明できる",
    common_misconception: "蒸気機関の発明だけで産業革命が起きたと考える",
    distractor_rationales: ["正解。資源・資本・市場の複合。", "不正解。対外開放と工業化。", "不正解。単一要因ではない。", "不正解。技術の一要素に過ぎない。"],
    basic_terms: "産業革命：機械工業による生産方式の変革、資本蓄積：投資可能な富の蓄積"
  }),
  q({
    domain: "人文社会科学",
    subdomain: "地理",
    difficulty_initial: 400,
    cognitive_type: "基本的な適用",
    question_text: "ケッペンの気候区分において、緯度や海からの距離など地点の位置そのものに基づく要因を何というか。",
    choices: ["消極的気候要因", "積極的気候要因", "地形的気候要因", "小気候要因"],
    correct_choice_index: 1,
    short_explanation: "積極的（太陽放射・緯度等）と消極的（海陸分布・地形等）に大別される。",
    detailed_explanation: "積極的要因は地点の天文・地理的位置に基づく。地形・局所要因は別分類。",
    learning_objective: "気候要因の積極的・消極的分類を説明できる",
    common_misconception: "気候は地形だけで決まると考える",
    distractor_rationales: ["不正解。海陸分布・地形など。", "正解。緯度・太陽高度など位置要因。", "不正解。地形は消極的要因の一部。", "不正解。局所的な気候変動。"],
    basic_terms: "積極的気候要因：緯度等の位置に基づく要因、ケッペン：気候区分の体系"
  }),
  q({
    domain: "人文社会科学",
    subdomain: "法学",
    difficulty_initial: 400,
    cognitive_type: "比較・分類",
    question_text: "罪刑法定主義の原則として最も適切なものはどれか。",
    choices: ["慣習だけで自由に処罰できる", "法律に定めのない行為は犯罪としない", "裁判官の裁量だけで刑を決める", "過去の法律に遡って処罰する"],
    correct_choice_index: 1,
    short_explanation: "罪刑法定主義は「法無き者は罪なし・刑なし」を意味する。",
    detailed_explanation: "慣習のみ・裁量のみ・遡及処罰は罪刑法定主義に反する。",
    learning_objective: "罪刑法定主義の基本内容を説明できる",
    common_misconception: "悪い行為はすべて法律がなくても処罰できると考える",
    distractor_rationales: ["不正解。法律の明確性を要求。", "正解。法律なき犯罪・刑罰なし。", "不正解。法律の根拠が必要。", "不正解。遡及適用は原則禁止。"],
    basic_terms: "罪刑法定主義：犯罪と刑罰は法律で定める原則、遡及適用：過去への法適用"
  }),
  q({
    domain: "人文社会科学",
    subdomain: "科学哲学",
    difficulty_initial: 400,
    cognitive_type: "誤解・境界",
    question_text: "カール・ポパーが科学理論の評価基準として重視したものはどれか。",
    choices: ["反証可能性（ファルシフィアビリティ）", "確認の回数のみ", "権威の承認", "一般常識との一致"],
    correct_choice_index: 0,
    short_explanation: "ポパーは科学は反証可能でなければならないと主張した。",
    detailed_explanation: "単なる確認は擬似科学も通す。権威・常識は科学的基準ではない。",
    learning_objective: "ポパーの反証主義の要点を説明できる",
    common_misconception: "科学は証明されれば真だと考える",
    distractor_rationales: ["正解。反証可能であること。", "不正解。帰納的確認だけでは不十分。", "不正解。権威主義ではない。", "不正解。常識は科学的基準ではない。"],
    basic_terms: "反証可能性：反例で理論を否定できる性質、ポパー：科学哲学者"
  }),
  // L500 ×4
  q({
    domain: "人文社会科学",
    subdomain: "経済学",
    difficulty_initial: 500,
    cognitive_type: "原理・因果",
    question_text: "リカードの比較優位の原理が自由貿易を支持する根拠として最も適切なものはどれか。",
    choices: ["すべての国がすべての品で絶対優位を持つから", "比較的に得意な品目に特化すれば双方が利益を得るから", "貿易は常に赤字になるから", "保護関税が常に最適だから"],
    correct_choice_index: 1,
    short_explanation: "比較優位は相対的な生産効率の差に基づき、専門化と貿易で双方の利益を生む。",
    detailed_explanation: "絶対優位がなくても比較優位があれば貿易利益が生じる。保護関税は原理の結論と逆。",
    learning_objective: "比較優位の原理を説明できる",
    common_misconception: "貿易利益は絶対優位がある国だけが得ると考える",
    distractor_rationales: ["不正解。絶対優位は十分条件ではない。", "正解。相対的優位による相互利益。", "不正解。貿易は利益を生みうる。", "不正解。自由貿易を支持する原理。"],
    basic_terms: "比較優位：相対的に低い機会費用、リカード：古典派経済学者"
  }),
  q({
    domain: "人文社会科学",
    subdomain: "心理学",
    difficulty_initial: 500,
    cognitive_type: "基本的な適用",
    question_text: "マズローの欲求階層説において、最も基本的な段階に位置する欲求はどれか。",
    choices: ["自己実現の欲求", "生理的欲求", "承認の欲求", "知的欲求"],
    correct_choice_index: 1,
    short_explanation: "マズローは生理的・安全・社会的・承認・自己実現の順に欲求が段階化されるとした。",
    detailed_explanation: "自己実現は最高段階。承認・知的欲求はより上位の段階。",
    learning_objective: "マズローの欲求階層の順序を説明できる",
    common_misconception: "すべての欲求が同時に同等に重要だと考える",
    distractor_rationales: ["不正解。最高段階の欲求。", "正解。食・睡眠などの生理的欲求。", "不正解。中位の社会的欲求。", "不正解。階層の標準的分類ではない。"],
    basic_terms: "欲求階層説：欲求が段階的に満たされるという理論、自己実現：潜在能力の発揮"
  }),
  q({
    domain: "人文社会科学",
    subdomain: "社会学",
    difficulty_initial: 500,
    cognitive_type: "比較・分類",
    question_text: "トニーズが区別した「ゲメンシャフト」と「ジーゲンシャフト」の対比として最も適切なものはどれか。",
    choices: ["共同体（感情的結合）と社会（合理的結合）", "都市と農村の気候差", "古代と現代の言語差", "男性と女性の役割差"],
    correct_choice_index: 0,
    short_explanation: "ゲメンシャフトは血縁・地缘に基づく共同体、ジーゲンシャフトは近代的合理的社会。",
    detailed_explanation: "トニーズは近代化に伴う社会結合の変化を概念化した。気候・言語・性別はこの対比の内容ではない。",
    learning_objective: "ゲメンシャフトとジーゲンシャフトの違いを説明できる",
    common_misconception: "両者を単なる都市・農村の違いだと考える",
    distractor_rationales: ["正解。共同体と合理的社会の対比。", "不正解。地理的気候の話。", "不正解。言語史の話。", "不正解。ジェンダー役割の話。"],
    basic_terms: "ゲメンシャフト：共同体、ジーゲンシャフト：社会（合理的社会）"
  }),
  q({
    domain: "人文社会科学",
    subdomain: "哲学",
    difficulty_initial: 500,
    cognitive_type: "誤解・境界",
    question_text: "功利主義（ユーティリタリアニズム）の倫理判断の基準として最も適切なものはどれか。",
    choices: ["行為者の動機の純粋さのみ", "最大多数の最大幸福（効用）の実現", "神の命令への従順のみ", "個人の権利の絶対的優先のみ"],
    correct_choice_index: 1,
    short_explanation: "ベンサム・ミルらは行為の善悪を結果としての効用・幸福の最大化で判断する。",
    detailed_explanation: "動機主義・神命論・権利絶対主義は功利主義の基準ではない。",
    learning_objective: "功利主義の基本原則を説明できる",
    common_misconception: "功利主義は利己主義と同一だと考える",
    distractor_rationales: ["不正解。結果主義である。", "正解。効用・幸福の最大化。", "不正解。神命論は別の倫理体系。", "不正解。権利論は対立的立場もある。"],
    basic_terms: "功利主義：効用最大化を善の基準とする倫理学、ベンサム：功利主義の創始者"
  }),
  // L600 ×3
  q({
    domain: "人文社会科学",
    subdomain: "政治学",
    difficulty_initial: 600,
    cognitive_type: "原理・因果",
    question_text: "国際関係理論におけるリアリズムの基本的前提として最も適切なものはどれか。",
    choices: ["国家は道徳的に協力し無政府状態は克服される", "国際体系は無政府状態であり国家は自国の権力と安全を追求する", "国家は消滅し国際機関のみが残る", "経済相互依存だけが外交を決定する"],
    correct_choice_index: 1,
    short_explanation: "リアリズムは無政府状態の下で国家が権力政治を行うとみなす。",
    detailed_explanation: "リベラリズムは協力・制度を重視。国家消滅論・経済決定論はリアリズムの前提ではない。",
    learning_objective: "リアリズムの基本前提を説明できる",
    common_misconception: "国際政治は国内政治と同じように法が機能すると考える",
    distractor_rationales: ["不正解。リベラル的見解。", "正解。無政府状態と権力追求。", "不正解。国家中心主義。", "不正解。単一要因論。"],
    basic_terms: "リアリズム：権力政治を重視する国際関係理論、無政府状態：最高権威の不在"
  }),
  q({
    domain: "人文社会科学",
    subdomain: "統計学",
    difficulty_initial: 600,
    cognitive_type: "基本的な適用",
    question_text: "ベイズ統計の推論において、観測データを得た後に仮説の確信度を更新する際に用いる定理はどれか。",
    choices: ["ベイズの定理", "ピタゴラスの定理", "中心極限定理", "大数の法則"],
    correct_choice_index: 0,
    short_explanation: "ベイズの定理は事前確率と尤度から事後確率を計算する。",
    detailed_explanation: "ピタゴラスは幾何、中心極限定理・大数の法則は頻度主義的結果。",
    learning_objective: "ベイズ推論の基本枠組みを説明できる",
    common_misconception: "ベイズ統計は頻度主義と同じ推論手順だと考える",
    distractor_rationales: ["正解。事前・尤度・事後の更新。", "不正解。幾何学の定理。", "不正解。標本平均の分布。", "不正解。標本平均の収束。"],
    basic_terms: "ベイズの定理：条件付き確率の更新公式、事前確率：データ前の確信度"
  }),
  q({
    domain: "人文社会科学",
    subdomain: "歴史",
    difficulty_initial: 600,
    cognitive_type: "比較・分類",
    question_text: "ブローデルらのアナール学派が歴史研究で重視した「長期（ロンク・デュレエ）」の意味として最も適切なものはどれか。",
    choices: ["単一事件の日時のみを扱う", "数十年から数百年にわたる構造的変化を分析する", "未来予測のみに焦点を当てる", "個人の日記のみを史料とする"],
    correct_choice_index: 1,
    short_explanation: "長期史は経済・社会・文化の緩やかな構造変化を長い時間軸で捉える。",
    detailed_explanation: "事件史・短期史とは対比される。未来予測・単一史料は方法論の焦点ではない。",
    learning_objective: "アナール学派の長期史観を説明できる",
    common_misconception: "歴史学は常に出来事の年表だけを扱うと考える",
    distractor_rationales: ["不正解。短期・事件史に近い。", "正解。長期の構造分析。", "不正解。史学の対象外。", "不正解。史料の一種に過ぎない。"],
    basic_terms: "アナール学派：フランスの歴史学派、長期：数十年〜数百年の時間軸"
  }),
  // L700 ×3
  q({
    domain: "人文社会科学",
    subdomain: "経済学",
    difficulty_initial: 700,
    cognitive_type: "原理・因果",
    question_text: "ゲーム理論におけるナッシュ均衡の定義として最も適切なものはどれか。",
    choices: ["すべての参加者が協力して全体最適を達成した状態", "各参加者が他者の戦略を所与として、自分の戦略を変更しても利得が改善しない状態", "一人の参加者だけが利得を最大化した状態", "戦略がランダムに選ばれた状態"],
    correct_choice_index: 1,
    short_explanation: "ナッシュ均衡は誰も一方的に戦略を変えて得をしない状態である。",
    detailed_explanation: "全体最適（パレート最適）とは一致しない場合がある。一人だけの最適・ランダムは定義に合わない。",
    learning_objective: "ナッシュ均衡の定義を説明できる",
    common_misconception: "ナッシュ均衡は常に社会的に最善だと考える",
    distractor_rationales: ["不正解。パレート最適・協力解。", "正解。相互最適反応の固定点。", "不正解。個人最適のみ。", "不正解。確率的選択。"],
    basic_terms: "ナッシュ均衡：誰も戦略変更の誘因がない状態、ゲーム理論：戦略的相互作用の分析"
  }),
  q({
    domain: "人文社会科学",
    subdomain: "心理学",
    difficulty_initial: 700,
    cognitive_type: "比較・分類",
    question_text: "ワイゼンとサントの「確証バイアス（確証的偏見）」が示す認知の傾向として最も適切なものはどれか。",
    choices: ["自分の仮説に合う情報を選好し、反証情報を軽視する", "すべての情報を公平に処理する", "記憶が完全に正確である", "他者の視点を常に優先する"],
    correct_choice_index: 0,
    short_explanation: "確証バイアスは既存の信念を支持する情報を過大評価する傾向である。",
    detailed_explanation: "公平処理・完全記憶・他者視点優先は確証バイアスの特徴と逆。",
    learning_objective: "確証バイアスの意味を説明できる",
    common_misconception: "人は常に客観的に情報を評価すると考える",
    distractor_rationales: ["正解。支持情報の選好と反証の軽視。", "不正解。バイアスの定義に反する。", "不正解。記憶の歪みは別問題。", "不正解。自己中心的バイアスに近い。"],
    basic_terms: "確証バイアス：自分の信念を支持する情報を選好する傾向、認知バイアス：判断の系統的歪み"
  }),
  q({
    domain: "人文社会科学",
    subdomain: "科学哲学",
    difficulty_initial: 700,
    cognitive_type: "誤解・境界",
    question_text: "トーマス・クーンの「パラダイム」概念が科学史において示すものとして最も適切なものはどれか。",
    choices: ["個人の主観的な好みのみ", "科学共同体が共有する理論・方法・問題意識の枠組み", "永遠不変の絶対真理", "実験データの無意味な集積"],
    correct_choice_index: 1,
    short_explanation: "パラダイムは通常科学の枠組みであり、科学革命で転換する。",
    detailed_explanation: "主観のみ・絶対真理・無意味なデータはクーンのパラダイム概念の趣旨ではない。",
    learning_objective: "クーンのパラダイム概念を説明できる",
    common_misconception: "科学は常に累積的に真理に近づくだけだと考える",
    distractor_rationales: ["不正解。共同体の共有枠組み。", "正解。理論・方法・価値の束。", "不正解。パラダイムは歴史的に転換する。", "不正解。データはパラダイム下で解釈される。"],
    basic_terms: "パラダイム：科学共同体の共有枠組み、科学革命：パラダイムの転換"
  })
];
