import { q } from "../lib/batch50-helpers.mjs";

export const medicalGap = [
  // L100 ×2
  q({
    domain: "医歯薬学",
    subdomain: "解剖",
    difficulty_initial: 100,
    cognitive_type: "用語・定義",
    question_text: "骨格を支え、体の運動に関与する組織はどれか。",
    choices: ["脂肪組織", "骨組織", "神経組織", "上皮組織"],
    correct_choice_index: 1,
    short_explanation: "骨組織は骨格を形成し、筋肉と連動して運動を支える。",
    detailed_explanation: "脂肪はエネルギー貯蔵、神経は情報伝達、上皮は体表・管腔を覆う。骨は支持・保護・造血の場を提供する。",
    learning_objective: "基本組織の種類と機能を区別できる",
    common_misconception: "骨は死んだ組織で機能しないと誤解する",
    distractor_rationales: ["不正解。エネルギー貯蔵組織。", "正解。骨格と運動の支持。", "不正解。興奮伝達組織。", "不正解。被覆組織。"],
    basic_terms: "骨組織：骨格を形成する結合組織、上皮組織：体表を覆う組織"
  }),
  q({
    domain: "医歯薬学",
    subdomain: "生理",
    difficulty_initial: 100,
    cognitive_type: "原理・因果",
    question_text: "赤血球の主な機能として最も適切なものはどれか。",
    choices: ["抗体の産生", "酸素の運搬", "血液の凝固", "老廃物の濾過"],
    correct_choice_index: 1,
    short_explanation: "赤血球のヘモグロビンが酸素を結合し全身に運ぶ。",
    detailed_explanation: "抗体産生はリンパ球、凝固は血小板と凝固因子、濾過は腎臓の機能。",
    learning_objective: "血液成分の基本機能を説明できる",
    common_misconception: "赤血球が免疫を担うと誤解する",
    distractor_rationales: ["不正解。リンパ球の機能。", "正解。ヘモグロビンによる O₂ 運搬。", "不正解。血小板等の機能。", "不正解。腎臓の機能。"],
    basic_terms: "赤血球：酸素運搬細胞、ヘモグロビン：酸素結合タンパク質"
  }),
  // L200 ×3
  q({
    domain: "医歯薬学",
    subdomain: "薬理",
    difficulty_initial: 200,
    cognitive_type: "基本的な適用",
    question_text: "細菌感染症の治療に用いられる薬剤の分類として正しいものはどれか。",
    choices: ["抗生物質", "解熱鎮痛薬", "抗ヒスタミン薬", "利尿薬"],
    correct_choice_index: 0,
    short_explanation: "抗生物質は細菌の増殖を抑制または殺菌する。",
    detailed_explanation: "ペニシリン等が代表例。解熱鎮痛薬は疼痛・発熱、抗ヒスタミンはアレルギー、利尿薬は尿量増加。",
    learning_objective: "主要薬効分類の適応を区別できる",
    common_misconception: "抗生物質がウイルス感染にも有効だと誤解する",
    distractor_rationales: ["正解。細菌感染治療薬。", "不正解。疼痛・発熱に用いる。", "不正解。アレルギー症状に用いる。", "不正解。尿量を増やす。"],
    basic_terms: "抗生物質：細菌感染治療薬、解熱鎮痛薬：疼痛・発熱緩和薬"
  }),
  q({
    domain: "医歯薬学",
    subdomain: "病理",
    difficulty_initial: 200,
    cognitive_type: "比較・分類",
    question_text: "炎症の局所所見として、ホット（熱感）・スウェリング（腫脹）・レッドネス（発赤）に加えて古典的に挙げられる所見はどれか。",
    choices: ["ペイン（疼痛）とロスオブファンクション（機能障害）", "発疹のみ", "体重増加", "意識消失のみ"],
    correct_choice_index: 0,
    short_explanation: "クラウディウスの5徴：発赤・腫脹・熱感・疼痛・機能障害。",
    detailed_explanation: "炎症は血管拡張と滲出により局所にこれらの徴候を生じる。",
    learning_objective: "炎症の基本徴候を説明できる",
    common_misconception: "炎症は常に感染を意味すると考える",
    distractor_rationales: ["正解。クラウディウスの炎症5徴。", "不正解。発疹は特定疾患の所見。", "不正解。全身症状であり局所徴候ではない。", "不正解。意識消失は炎症の定義徴候ではない。"],
    basic_terms: "炎症：組織の血管反応と細胞浸潤、クラウディウスの5徴：炎症の局所所見"
  }),
  q({
    domain: "医歯薬学",
    subdomain: "免疫",
    difficulty_initial: 200,
    cognitive_type: "誤解・境界",
    question_text: "ワクチン接種の目的として最も適切なものはどれか。",
    choices: ["感染症に対する免疫を獲得・強化する", "既に発症した感染を即座に治癒する", "すべてのウイルスを体内から除去する", "抗生物質の投与を不要にする"],
    correct_choice_index: 0,
    short_explanation: "ワクチンは抗原を提示し、予防的な免疫獲得を促す。",
    detailed_explanation: "治療薬ではなく予防。抗生物質は細菌感染治療用であり、ワクチンとは目的が異なる。",
    learning_objective: "ワクチンの予防的役割を説明できる",
    common_misconception: "ワクチンは発症後の治療薬だと誤解する",
    distractor_rationales: ["正解。予防的免疫獲得。", "不正解。治療薬ではない。", "不正解。全ウイルス除去は不可能。", "不正解。抗生物質とは別の概念。"],
    basic_terms: "ワクチン：予防接種用の免疫原、免疫：病原体への防御能"
  }),
  // L300 ×5
  q({
    domain: "医歯薬学",
    subdomain: "生化学",
    difficulty_initial: 300,
    cognitive_type: "用語・定義",
    question_text: "DNA のヌクレオチドを構成する3つの成分として正しい組み合わせはどれか。",
    choices: ["塩基・糖・リン酸", "アミノ酸・糖・脂質", "塩基・コレステロール・リン酸", "グルコース・脂肪酸・塩基"],
    correct_choice_index: 0,
    short_explanation: "ヌクレオチドは塩基・ペントース（デオキシリボース）・リン酸からなる。",
    detailed_explanation: "アミノ酸はタンパク質の構成単位。コレステロールや脂肪酸は脂質関連成分。",
    learning_objective: "核酸の基本構成を説明できる",
    common_misconception: "DNA はアミノ酸からなると誤解する",
    distractor_rationales: ["正解。ヌクレオチドの三成分。", "不正解。タンパク質の構成単位を含む。", "不正解。コレステロールは核酸成分ではない。", "不正解。代謝物の混同。"],
    basic_terms: "ヌクレオチド：核酸の構成単位、塩基：A・T・G・C"
  }),
  q({
    domain: "医歯薬学",
    subdomain: "微生物",
    difficulty_initial: 300,
    cognitive_type: "原理・因果",
    question_text: "ペニシリンの抗菌作用の主な標的はどれか。",
    choices: ["細菌の細胞壁合成", "ウイルスの複製", "ヒト細胞膜のコレステロール", "真菌の核膜"],
    correct_choice_index: 0,
    short_explanation: "β-ラクタム系抗生物質はペプチドグリカン合成を阻害し細胞壁形成を妨げる。",
    detailed_explanation: "ウイルスには細胞壁がない。真菌には別の細胞壁成分があり、抗真菌薬が用いられる。",
    learning_objective: "β-ラクタム抗生物質の作用機序を説明できる",
    common_misconception: "抗生物質がウイルスにも効くと誤解する",
    distractor_rationales: ["正解。細菌細胞壁合成の阻害。", "不正解。ウイルスには細胞壁がない。", "不正解。ヒト細胞を標的としない。", "不正解。真菌の標的ではない。"],
    basic_terms: "ペプチドグリカン：細菌細胞壁の主要成分、β-ラクタム：細胞壁合成阻害剤"
  }),
  q({
    domain: "医歯薬学",
    subdomain: "歯学",
    difficulty_initial: 300,
    cognitive_type: "基本的な適用",
    question_text: "歯のエナメル質（釉質）の主成分として正しいものはどれか。",
    choices: ["コラーゲン", "ヒドロキシアパタイト（リン酸カルシウム）", "ケラチン", "ヘモグロビン"],
    correct_choice_index: 1,
    short_explanation: "エナメル質はヒドロキシアパタイト結晶が主体の高度石灰化組織。",
    detailed_explanation: "象牙質はコラーゲンを含む。ケラチンは角化組織、ヘモグロビンは血液タンパク質。",
    learning_objective: "歯の硬組織の組成を説明できる",
    common_misconception: "エナメル質はコラーゲン主体だと誤解する",
    distractor_rationales: ["不正解。象牙質の主成分。", "正解。エナメル質の無機主成分。", "不正解。角化タンパク質。", "不正解。血液タンパク質。"],
    basic_terms: "エナメル質：歯の最外層の石灰化組織、ヒドロキシアパタイト：リン酸カルシウム結晶"
  }),
  q({
    domain: "医歯薬学",
    subdomain: "薬学",
    difficulty_initial: 300,
    cognitive_type: "比較・分類",
    question_text: "薬物の投与経路のうち、消化管を経由して吸収される経路はどれか。",
    choices: ["経口投与", "静脈内投与", "吸入投与", "経皮投与"],
    correct_choice_index: 0,
    short_explanation: "経口投与は消化管吸収により全身へ分布する。",
    detailed_explanation: "静脈内は直接血流へ、吸入は肺胞吸収、経皮は皮膚透過。",
    learning_objective: "主要な投与経路を区別できる",
    common_misconception: "すべての薬は注射が最も効果的だと考える",
    distractor_rationales: ["正解。消化管吸収。", "不正解。直接血流投与。", "不正解。肺胞から吸収。", "不正解。皮膚から吸収。"],
    basic_terms: "経口投与：内服による投与、バイオアベイラビリティ：吸収利用率"
  }),
  q({
    domain: "医歯薬学",
    subdomain: "分子腫瘍学",
    difficulty_initial: 300,
    cognitive_type: "誤解・境界",
    question_text: "がん細胞の特徴として最も適切なものはどれか。",
    choices: ["細胞分裂が完全に停止している", "無秩序な増殖と浸潤能を示す", "必ずウイルス感染によって生じる", "常に良性である"],
    correct_choice_index: 1,
    short_explanation: "がんは制御を失った増殖・浸潤・転移能を持つ。",
    detailed_explanation: "がんの原因は多因子（遺伝子変異・環境等）。ウイルスは一部の原因に過ぎない。",
    learning_objective: "がん細胞の基本的特徴を説明できる",
    common_misconception: "がんはすべてウイルスが原因だと誤解する",
    distractor_rationales: ["不正解。むしろ異常な増殖。", "正解。無秩序増殖と浸潤。", "不正解。原因は多様。", "不正解。悪性腫瘍の特徴に反する。"],
    basic_terms: "悪性腫瘍：浸潤・転移能を持つ腫瘍、浸潤：周囲組織への侵入"
  }),
  // L400 ×5
  q({
    domain: "医歯薬学",
    subdomain: "解剖",
    difficulty_initial: 400,
    cognitive_type: "用語・定義",
    question_text: "横隔膜の直上に位置し、肺を収める胸腔の上部にある腔はどれか。",
    choices: ["腹腔", "胸腔", "骨盤腔", "硬膜外腔"],
    correct_choice_index: 1,
    short_explanation: "胸腔は横隔膜上方にあり、肺と心臓を収める。",
    detailed_explanation: "腹腔は横隔膜下方で消化器・肝臓等を収める。骨盤腔は骨盤内、硬膜外腔は脊椎周囲。",
    learning_objective: "体腔の位置関係を説明できる",
    common_misconception: "肺は腹腔にあると誤解する",
    distractor_rationales: ["不正解。横隔膜下方の体腔。", "正解。肺を収める体腔。", "不正解。骨盤内の腔。", "不正解。脊椎周囲の腔。"],
    basic_terms: "胸腔：肺を収める体腔、横隔膜：呼吸筋として胸腔と腹腔を隔てる"
  }),
  q({
    domain: "医歯薬学",
    subdomain: "生理",
    difficulty_initial: 400,
    cognitive_type: "原理・因果",
    question_text: "血糖値上昇時に膵臓β細胞から分泌され、末梢組織でグルコース取り込みを促進するホルモンはどれか。",
    choices: ["グルカゴン", "インスリン", "アドレナリン", "甲状腺ホルモン"],
    correct_choice_index: 1,
    short_explanation: "インスリンは血糖降下作用を持ち、グルコースの細胞内取り込みを促す。",
    detailed_explanation: "グルカゴンは血糖上昇、アドレナリンはストレス応答、甲状腺ホルモンは代謝亢進。",
    learning_objective: "血糖調節ホルモンの役割を説明できる",
    common_misconception: "グルカゴンとインスリンの作用を混同する",
    distractor_rationales: ["不正解。血糖上昇ホルモン。", "正解。血糖降下・取り込み促進。", "不正解。カテコールアミン。", "不正解。基礎代謝調節。"],
    basic_terms: "インスリン：血糖降下ホルモン、グルカゴン：血糖上昇ホルモン"
  }),
  q({
    domain: "医歯薬学",
    subdomain: "薬理",
    difficulty_initial: 400,
    cognitive_type: "基本的な適用",
    question_text: "アセチルコリンエステラーゼ阻害薬の代表的適応として最も適切なものはどれか。",
    choices: ["重症筋無力症", "高血圧症", "糖尿病", "うつ病"],
    correct_choice_index: 0,
    short_explanation: "ネオスチグミン等は神経筋接合部のアセチルコリン分解を阻害し筋収縮を改善する。",
    detailed_explanation: "重症筋無力症は抗アセチルコリン受容体抗体により神経伝達が低下する。",
    learning_objective: "酵素阻害薬の適応例を説明できる",
    common_misconception: "すべての神経系疾患に同一薬剤が使えると考える",
    distractor_rationales: ["正解。神経筋接合部の伝達改善。", "不正解。降圧薬とは異なる。", "不正解。インスリン等が主。", "不正解。抗うつ薬とは異なる。"],
    basic_terms: "アセチルコリンエステラーゼ：神経伝達物質を分解する酵素、重症筋無力症：神経筋疾患"
  }),
  q({
    domain: "医歯薬学",
    subdomain: "病理",
    difficulty_initial: 400,
    cognitive_type: "比較・分類",
    question_text: "アポトーシス（細胞死）の特徴として最も適切なものはどれか。",
    choices: ["周囲組織への強い炎症を必ず引き起こす", "プログラムされた細胞死で細胞は膜完整性を保ちながら小さくなる", "必ず病原体感染に伴う", "壊死と同じ機序である"],
    correct_choice_index: 1,
    short_explanation: "アポトーシスは制御された細胞死で、炎症反応は最小限。",
    detailed_explanation: "壊死は膜破綻と炎症を伴う。アポトーシスは発育・恒常性維持に重要。",
    learning_objective: "アポトーシスと壊死の違いを説明できる",
    common_misconception: "すべての細胞死が壊死だと考える",
    distractor_rationales: ["不正解。炎症は軽微。", "正解。プログラム死の特徴。", "不正解。生理的にも起こる。", "不正解。壊死とは機序が異なる。"],
    basic_terms: "アポトーシス：プログラムされた細胞死、壊死：受傷による細胞死"
  }),
  q({
    domain: "医歯薬学",
    subdomain: "免疫",
    difficulty_initial: 400,
    cognitive_type: "誤解・境界",
    question_text: "ヒト免疫グロブリン（抗体）のうち、粘膜免疫やアレルギー反応で重要な Ig クラスはどれか。",
    choices: ["IgG", "IgE", "IgM", "IgD"],
    correct_choice_index: 1,
    short_explanation: "IgE はアレルギー・寄生虫免疫に関与し、肥満細胞表面に結合する。",
    detailed_explanation: "IgG は血中の主抗体、IgM は初期応答のペンタマー、IgD は B 細胞受容体。",
    learning_objective: "抗体クラスの機能的違いを説明できる",
    common_misconception: "すべての抗体が同じ役割だと考える",
    distractor_rationales: ["不正解。血中の主抗体。", "正解。アレルギー・寄生虫免疫。", "不正解。初期免疫応答。", "不正解。B 細胞受容体として主に機能。"],
    basic_terms: "IgE：アレルギー関連抗体、IgG：血中の主要抗体"
  }),
  // L500 ×3
  q({
    domain: "医歯薬学",
    subdomain: "生化学",
    difficulty_initial: 500,
    cognitive_type: "用語・定義",
    question_text: "解糖系（グリコリシス）の最終産物として、好気的条件下でミトコンドリアに引き渡される主要分子はどれか。",
    choices: ["ピルビン酸", "アセチルCoA", "乳酸", "クエン酸"],
    correct_choice_index: 0,
    short_explanation: "解糖系はグルコースをピルビン酸に変換する。",
    detailed_explanation: "ピルビン酸は好気下でアセチルCoA に変換され TCA 回路へ。嫌気下では乳酸へ還元。",
    learning_objective: "解糖系の産物と代謝経路を説明できる",
    common_misconception: "解糖系の最終産物が常に乳酸だと誤解する",
    distractor_rationales: ["正解。解糖系の直接産物。", "不正解。ピルビン酸からの変換産物。", "不正解。嫌気条件下の還元産物。", "不正解。TCA 回路の中間体。"],
    basic_terms: "解糖系：グルコース分解経路、ピルビン酸：解糖系の終産物"
  }),
  q({
    domain: "医歯薬学",
    subdomain: "微生物",
    difficulty_initial: 500,
    cognitive_type: "原理・因果",
    question_text: "抗生物質耐性菌の出現を抑制するための抗菌薬使用原則として最も適切なものはどれか。",
    choices: ["症状が軽い場合でも広域抗生物質を長期投与する", "必要な場合に適切な薬剤を十分量・適切期間投与する", "常に最新の抗生物質を予防的に投与する", "複数の抗生物質を無作為に併用する"],
    correct_choice_index: 1,
    short_explanation: "適正使用（適応・薬剤・用量・期間）が耐性出現を抑制する。",
    detailed_explanation: "不適切使用は選択圧により耐性菌を増やす。予防投与は厳格な適応が必要。",
    learning_objective: "抗菌薬適正使用の原則を説明できる",
    common_misconception: "抗生物質は予防的に常時使うべきだと誤解する",
    distractor_rationales: ["不正解。耐性菌を選択する。", "正解。適正使用の基本。", "不正解。予防投与の乱用。", "不正解。無作為併用は耐性リスク。"],
    basic_terms: "抗菌薬適正使用：適応・薬剤・用量・期間の最適化、耐性：薬剤に対する感受性低下"
  }),
  q({
    domain: "医歯薬学",
    subdomain: "歯学",
    difficulty_initial: 500,
    cognitive_type: "基本的な適用",
    question_text: "歯周組織の破壊を進行させる主要な病因として最も適切なものはどれか。",
    choices: ["プラーク内の細菌と宿主の免疫炎症反応", "フッ化物の過剰摂取のみ", "歯ブラシの使用", "唾液分泌の増加"],
    correct_choice_index: 0,
    short_explanation: "歯周病はプラーク細菌とそれに対する炎症反応により組織破壊が進む。",
    detailed_explanation: "フッ化物はう蝕予防、ブラシはプラーク除去、唾液は自浄作用。",
    learning_objective: "歯周病の病因を説明できる",
    common_misconception: "歯周病は加齢のみで起こると誤解する",
    distractor_rationales: ["正解。細菌と炎症の相互作用。", "不正解。フッ化物はう蝕予防。", "不正解。プラーク管理は予防。", "不正解。唾液は保護的。"],
    basic_terms: "歯周病：歯周組織の慢性炎症、プラーク：歯面の細菌バイオフィルム"
  }),
  // L600 ×3
  q({
    domain: "医歯薬学",
    subdomain: "薬理",
    difficulty_initial: 600,
    cognitive_type: "原理・因果",
    question_text: "β遮断薬の作用機序として最も適切なものはどれか。",
    choices: ["βアドレナリン受容体を遮断し心拍数・収縮力を低下させる", "アンジオテンシン変換酵素を阻害する", "カルシウムチャネルを直接開く", "ヒスタミンH1受容体を刺激する"],
    correct_choice_index: 0,
    short_explanation: "β遮断薬はβ受容体を競合的に遮断し、交感神経刺激効果を抑制する。",
    detailed_explanation: "ACE 阻害薬、カルシウム拮抗薬、抗ヒスタミン薬はそれぞれ異なる標的。",
    learning_objective: "β遮断薬の作用機序を説明できる",
    common_misconception: "すべての降圧薬が同じ機序だと考える",
    distractor_rationales: ["正解。β受容体遮断。", "不正解。ACE 阻害薬の機序。", "不正解。Ca 拮抗薬とは異なる。", "不正解。抗ヒスタミン作用。"],
    basic_terms: "β遮断薬：βアドレナリン受容体遮断薬、交感神経：ストレス応答系"
  }),
  q({
    domain: "医歯薬学",
    subdomain: "病理",
    difficulty_initial: 600,
    cognitive_type: "比較・分類",
    question_text: "血栓（thrombus）と塞栓（embolus）の違いとして正しいものはどれか。",
    choices: ["血栓は血管内で形成され、塞栓は血流に乗って移動し血管を閉塞する", "血栓は常に感染による", "塞栓は血管内で形成される", "両者は同一概念である"],
    correct_choice_index: 0,
    short_explanation: "血栓は局所形成、塞栓は遠隔で閉塞を起こす移動体。",
    detailed_explanation: "血栓から離脱したものが塞栓となる（血栓塞栓）。脂肪・空気塞栓もある。",
    learning_objective: "血栓と塞栓の概念を区別できる",
    common_misconception: "血栓と塞栓を同一視する",
    distractor_rationales: ["正解。形成部位と移動の違い。", "不正解。血栓の原因は多様。", "不正解。塞栓は移動体。", "不正解。関連はあるが概念は異なる。"],
    basic_terms: "血栓：血管内凝固塊、塞栓：血流に運ばれ閉塞する物質"
  }),
  q({
    domain: "医歯薬学",
    subdomain: "薬学",
    difficulty_initial: 600,
    cognitive_type: "基本的な適用",
    question_text: "薬物動態の「バイオアベイラビリティ」が示すものとして最も適切なものはどれか。",
    choices: ["投与量に対する血中濃度の変化速度", "投与された薬物のうち全身循環に到達した割合", "薬物の半減期の長さ", "代謝酵素の活性"],
    correct_choice_index: 1,
    short_explanation: "バイオアベイラビリティは吸収され全身に利用可能になった薬物の割合。",
    detailed_explanation: "経口投与では初回通過効果で低下しうる。静脈内投与は定義上100%。",
    learning_objective: "バイオアベイラビリティの意味を説明できる",
    common_misconception: "投与量がそのまま血中濃度になると考える",
    distractor_rationales: ["不正解。吸収速度の指標。", "正解。全身利用可能割合。", "不正解。消失の指標。", "不正解。代謝能の指標。"],
    basic_terms: "バイオアベイラビリティ：全身吸収利用率、初回通過効果：肝での初回代謝"
  }),
  // L700 ×3
  q({
    domain: "医歯薬学",
    subdomain: "生化学",
    difficulty_initial: 700,
    cognitive_type: "原理・因果",
    question_text: "電子伝達系において、最終電子受容体として分子状酸素（O₂）が必要な理由として最も適切なものはどれか。",
    choices: ["O₂ が直接 ATP を合成する", "O₂ が電子を受け取り H₂O を生成し、電子伝達を完結させる", "O₂ が解糖系を開始する", "O₂ が TCA 回路の基質である"],
    correct_choice_index: 1,
    short_explanation: "好気性呼吸では O₂ が最終電子受容体となり水を生成する。",
    detailed_explanation: "電子伝達系の電子は O₂ に渡され H₂O となる。この過程でプロトン勾配駆動 ATP 合成。",
    learning_objective: "好気性呼吸における酸素の役割を説明できる",
    common_misconception: "酸素が直接 ATP を作ると誤解する",
    distractor_rationales: ["不正解。ATP 合成は ATP 合成酵素が行う。", "正解。最終電子受容体としての O₂。", "不正解。解糖は酸素不要。", "不正解。TCA 回路の基質ではない。"],
    basic_terms: "電子伝達系：ミトコンドリア内膜の電子伝達、最終電子受容体：O₂"
  }),
  q({
    domain: "医歯薬学",
    subdomain: "免疫",
    difficulty_initial: 700,
    cognitive_type: "比較・分類",
    question_text: "MHC（主要組織適合遺伝子複合体）クラスIとクラスIIの抗原提示の違いとして正しいものはどれか。",
    choices: ["クラスIは細胞内抗原をCD8+ T細胞に、クラスIIは細胞外抗原をCD4+ T細胞に提示する", "クラスIはB細胞のみに存在する", "クラスIIはすべての有核細胞に発現する", "両者は同一の抗原提示経路である"],
    correct_choice_index: 0,
    short_explanation: "クラスIは内在性抗原→CD8+、クラスIIは外来性抗原→CD4+。",
    detailed_explanation: "クラスIは有核細胞に広く発現、クラスIIは主に抗原提示細胞に発現。",
    learning_objective: "MHC クラスI/II の抗原提示経路を説明できる",
    common_misconception: "MHC I と II が同じ T 細胞に提示すると誤解する",
    distractor_rationales: ["正解。提示経路と T 細胞サブセットの対応。", "不正解。クラスIは広く発現。", "不正解。クラスIIは主に APC。", "不正解。経路は異なる。"],
    basic_terms: "MHC：抗原提示分子、CD8+ T細胞：細胞傷害性 T 細胞"
  }),
  q({
    domain: "医歯薬学",
    subdomain: "分子腫瘍学",
    difficulty_initial: 700,
    cognitive_type: "誤解・境界",
    question_text: "p53 遺伝子の腫瘍抑制機能として最も適切なものはどれか。",
    choices: ["細胞周期のチェックポイントで DNA 損傷時に細胞周期停止またはアポトーシスを誘導する", "細胞分裂を無条件に促進する", "血管新生を必ず促進する", "すべてのがんで過剰発現する"],
    correct_choice_index: 0,
    short_explanation: "p53 はゲノムの番人として損傷応答で細胞死または修復を制御する。",
    detailed_explanation: "p53 変異・失活は多くのがんで見られる。過剰発現ではなく機能喪失が問題。",
    learning_objective: "主要腫瘍抑制遺伝子の機能を説明できる",
    common_misconception: "p53 はがんを促進する遺伝子だと誤解する",
    distractor_rationales: ["正解。DNA 損傷応答の中心的役割。", "不正解。増殖促進はオンコジーンの特徴。", "不正解。血管新生促進ではない。", "不正解。機能喪失が多い。"],
    basic_terms: "p53：腫瘍抑制遺伝子、チェックポイント：細胞周期の監視点"
  })
];
