import { q } from "../lib/batch50-helpers.mjs";

export const earthGap = [
  q({
    domain: "地学",
    subdomain: "気象学",
    difficulty_initial: 100,
    cognitive_type: "用語・定義",
    question_text: "空に浮かぶ白い綿のようなものの正しい名前はどれか。",
    choices: ["雲", "霧", "虹", "雷"],
    correct_choice_index: 0,
    short_explanation: "空高くに見える水蒸気の集まりは雲である。",
    detailed_explanation: "雲は大気中の水滴や氷晶が集まって見えるもの。地面近くの霧と成分は似るが、高度が異なる。",
    learning_objective: "雲と霧など大気の基本的な見え方を区別できる",
    common_misconception: "空の白いものをすべて霧と呼ぶ",
    distractor_rationales: ["正解。空高くに浮かぶ水蒸気の集まり。", "不正解。地面近くにかかるもの。", "不正解。光の屈折でできる現象。", "不正解。放電現象。"],
    basic_terms: "雲：大気中の水滴・氷晶の集まり、霧：地表近くの雲"
  }),
  q({
    domain: "地学",
    subdomain: "地質学",
    difficulty_initial: 200,
    cognitive_type: "比較・分類",
    question_text: "火山噴出物のうち、液体状で流れ出すものはどれか。",
    choices: ["火山灰", "溶岩", "軽石", "火山弾"],
    correct_choice_index: 1,
    short_explanation: "地表で流れる高温の岩石熔融体は溶岩と呼ぶ。",
    detailed_explanation: "マグマが地表に出ると溶岩となる。火山灰は細粒の固体、軽石・火山弾は固体の噴出物。",
    learning_objective: "火山噴出物の種類を区別できる",
    common_misconception: "マグマと溶岩を同じ語で使う",
    distractor_rationales: ["不正解。細かい固体粒子。", "正解。地表で流れる熔融岩石。", "不正解。多孔質の固体。", "不正解。塊状の固体噴出物。"],
    basic_terms: "溶岩：地表に出たマグマ、マグマ：地下の岩石熔融体"
  }),
  q({
    domain: "地学",
    subdomain: "気象学",
    difficulty_initial: 200,
    cognitive_type: "原理・因果",
    question_text: "海から陸に向かって昼間に吹きやすい風として正しいものはどれか。",
    choices: ["季節風", "海風", "偏西風", "フェーン風"],
    correct_choice_index: 1,
    short_explanation: "昼間は陸が海より温まり、海から陸へ海風が吹く。",
    detailed_explanation: "海陸熱容量差により昼は陸上の気圧が低くなり、海から陸へ海風が吹く。夜は陸風。",
    learning_objective: "海陸風の発生機構を説明できる",
    common_misconception: "常に陸から海へ風が吹くと考える",
    distractor_rationales: ["不正解。季節スケールの風系。", "正解。昼間の海から陸への局地風。", "不正解。中緯度の偏西風帯の風。", "不正解。山を越える下降風。"],
    basic_terms: "海風：海から陸へ吹く風、海陸風：昼夜の温度差による局地循環"
  }),
  q({
    domain: "地学",
    subdomain: "鉱物学",
    difficulty_initial: 200,
    cognitive_type: "用語・定義",
    question_text: "石英（シリカ）の化学組成として正しいものはどれか。",
    choices: ["SiO₂", "CaCO₃", "NaCl", "Fe₂O₃"],
    correct_choice_index: 0,
    short_explanation: "石英は二酸化ケイ素 SiO₂ でできている。",
    detailed_explanation: "石英は地殻中に広く分布する鉱物で組成は SiO₂。方解石は CaCO₃、塩化ナトリウムは NaCl。",
    learning_objective: "代表的鉱物の化学組成を識別できる",
    common_misconception: "石英を炭酸カルシウムと混同する",
    distractor_rationales: ["正解。石英の化学式。", "不正解。方解石などの組成。", "不正解。岩塩の組成。", "不正解。酸化鉄鉱物の組成。"],
    basic_terms: "石英：二酸化ケイ素からなる鉱物、化学組成：物質を構成する元素の比"
  }),
  q({
    domain: "地学",
    subdomain: "海洋学",
    difficulty_initial: 200,
    cognitive_type: "基本的な適用",
    question_text: "満潮と干潮がおよそ1日に2回ずつ起こる主な原因はどれか。",
    choices: ["地球の自転", "月の公転と引力", "太陽の黒点", "海流の変化"],
    correct_choice_index: 1,
    short_explanation: "月の引力と地球・月系の運動により潮汐が1日約2回生じる。",
    detailed_explanation: "月の引力による引潮力が主因。地球の自転と組み合わさり、多くの海岸で半日周期の潮汐となる。",
    learning_objective: "潮汐の基本的な成因を説明できる",
    common_misconception: "潮汐は地球の自転だけで決まると考える",
    distractor_rationales: ["不正解。自転は周期に関与するが主因は引力。", "正解。月の引力が潮汐の主因。", "不正解。黒点とは無関係。", "不正解。海流とは別現象。"],
    basic_terms: "潮汐：海面の周期的な昇降、引潮力：天体の引力による差"
  }),
  q({
    domain: "地学",
    subdomain: "宇宙惑星科学",
    difficulty_initial: 200,
    cognitive_type: "比較・分類",
    question_text: "太陽系の惑星のうち、地球の軌道の内側に位置する惑星として正しい組合せはどれか。",
    choices: ["水星と金星", "火星と木星", "土星と天王星", "海王星のみ"],
    correct_choice_index: 0,
    short_explanation: "地球より太陽に近い内側惑星は水星と金星である。",
    detailed_explanation: "太陽からの順に水星・金星・地球・火星…。内側惑星（地球型惑星の内側組）は水星と金星。",
    learning_objective: "太陽系惑星の軌道配置を理解できる",
    common_misconception: "火星が地球の内側にあると考える",
    distractor_rationales: ["正解。地球より太陽側の惑星。", "不正解。どちらも地球の外側。", "不正解。外惑星。", "不正解。最も外側の惑星。"],
    basic_terms: "惑星：太陽の周りを公転する天体、公転：より大きな天体の周りの運動"
  }),
  q({
    domain: "地学",
    subdomain: "地質学",
    difficulty_initial: 300,
    cognitive_type: "原理・因果",
    question_text: "プレートテクトニクスにおいて、大洋プレートが大陸プレートの下に沈み込む境界はどれか。",
    choices: ["発散境界", "収束境界", "トランスフォーム境界", "ホットスポット"],
    correct_choice_index: 1,
    short_explanation: "プレートが向かい合って衝突し一方が沈み込むのは収束境界。",
    detailed_explanation: "収束境界では大洋プレートが大陸プレート下に沈み込み、海溝・火山弧を形成する。",
    learning_objective: "プレート境界の3類型と地質現象を対応づけられる",
    common_misconception: "すべてのプレート境界で沈み込みが起こると誤解する",
    distractor_rationales: ["不正解。プレートが離れる境界。", "正解。プレートが衝突し沈み込む境界。", "不正解。横断断層による横ずれ境界。", "不正解。プレート内部のマントルプルーム。"],
    basic_terms: "プレートテクトニクス：岩石圏プレートの運動理論、収束境界：プレートが衝突する境界"
  }),
  q({
    domain: "地学",
    subdomain: "気象学",
    difficulty_initial: 300,
    cognitive_type: "基本的な適用",
    question_text: "前線面に沿って暖かい空気が寒冷な空気の上に乗り上げる前線はどれか。",
    choices: ["寒冷前線", "温暖前線", "停滞前線", "偏西風"],
    correct_choice_index: 1,
    short_explanation: "温暖前線では暖気が寒気の上に緩やかに上昇する。",
    detailed_explanation: "温暖前線では暖気が寒気面に沿って上昇し、広範囲の雲・降水をもたらす。寒冷前線は逆の配置。",
    learning_objective: "温暖前線と寒冷前線の構造の違いを説明できる",
    common_misconception: "前線では常に寒気が暖気の上に乗ると考える",
    distractor_rationales: ["不正解。寒気が暖気の下に楔状に入る。", "正解。暖気が寒気の上に乗り上げる。", "不正解。前線が停滞した状態。", "不正解。大気大循環の偏西風帯。"],
    basic_terms: "温暖前線：暖気が寒気の上に上昇する前線、前線：性質の異なる気団の境界"
  }),
  q({
    domain: "地学",
    subdomain: "地球化学",
    difficulty_initial: 300,
    cognitive_type: "比較・分類",
    question_text: "岩石の三大分類のうち、火山活動などでマグマが冷え固まってできた岩石はどれか。",
    choices: ["火成岩", "堆積岩", "変成岩", "隕石"],
    correct_choice_index: 0,
    short_explanation: "マグマの冷却・固化によりできた岩石は火成岩である。",
    detailed_explanation: "火成岩はマグマ由来。堆積岩は堆積物の固結、変成岩は既存岩石の変質により形成。",
    learning_objective: "三大岩石の成因を区別できる",
    common_misconception: "すべての岩石が堆積によってできると考える",
    distractor_rationales: ["正解。マグマ冷却により形成。", "不正解。堆積・固結により形成。", "不正解。変質作用により形成。", "不正解。宇宙由来の岩石。"],
    basic_terms: "火成岩：マグマからできた岩石、堆積岩：堆積物が固まった岩石"
  }),
  q({
    domain: "地学",
    subdomain: "地震学",
    difficulty_initial: 300,
    cognitive_type: "用語・定義",
    question_text: "地震の規模をマグニチュードで表すとき、マグニチュードが1大きくなると解放されるエネルギーはおよそ何倍になるか。",
    choices: ["約2倍", "約10倍", "約32倍", "約100倍"],
    correct_choice_index: 2,
    short_explanation: "マグニチュード1増でエネルギーは約32倍（10^1.5倍）。",
    detailed_explanation: "マグニチュードとエネルギーの関係は log E ∝ M。M が1増えるとエネルギーは約31.6倍。",
    learning_objective: "マグニチュードと地震エネルギーの関係を理解できる",
    common_misconception: "マグニチュードとエネルギーが比例すると考える",
    distractor_rationales: ["不正解。対数スケールなので2倍ではない。", "不正解。10倍は過小。", "正解。10^1.5 ≈ 32倍。", "不正解。100倍は過大。"],
    basic_terms: "マグニチュード：地震の規模の指標、対数スケール：値の差が倍数を表す尺度"
  }),
  q({
    domain: "地学",
    subdomain: "地質学",
    difficulty_initial: 400,
    cognitive_type: "原理・因果",
    question_text: "背斜構造の中央部に古い地層が出露し、两翼に新しい地層が並ぶ理由として最も適切なものはどれか。",
    choices: ["地層が中央で逆転して折り曲げられたため", "中央だけ侵食が進まなかったため", "新しい地層だけが中央に堆積したため", "断層で中央が押し下げられたため"],
    correct_choice_index: 0,
    short_explanation: "背斜は層状地層が上に凸に曲がり、中央で古い層が露出する。",
    detailed_explanation: "背斜は褶曲構造の一種。層の折り曲げにより核部に古層、翼に新層が配列する。",
    learning_objective: "背斜・向斜の構造と地層年代の関係を説明できる",
    common_misconception: "中央に新しい地層が来ると考える（向斜と混同）",
    distractor_rationales: ["正解。褶曲により古層が核部に出る。", "不正解。侵食は露出の要因だが構造の本質は褶曲。", "不正解。堆積順序の問題ではない。", "不正解。背斜は隆起構造。"],
    basic_terms: "背斜：層が上に凸に曲がった褶曲、向斜：層が下に凹に曲がった褶曲"
  }),
  q({
    domain: "地学",
    subdomain: "気象学",
    difficulty_initial: 400,
    cognitive_type: "基本的な適用",
    question_text: "乾燥断熱減率が湿潤断熱減率より大きい理由として最も適切なものはどれか。",
    choices: ["乾燥空気の上昇では水蒸気凝結による潜熱放出がないため", "乾燥空気は常に温度が低いため", "湿潤空気は圧力が高いため", "乾燥空気には水蒸気が多いため"],
    correct_choice_index: 0,
    short_explanation: "湿潤上昇では凝結潜熱が放出され温度降下が緩やかになる。",
    detailed_explanation: "乾燥断熱減率 ≈ 1°C/100m。湿潤では水蒸気凝結で潜熱が補われ、約0.5–0.6°C/100m と小さい。",
    learning_objective: "乾燥断熱と湿潤断熱の違いを潜熱で説明できる",
    common_misconception: "乾燥と湿潤で減率が同じだと考える",
    distractor_rationales: ["正解。潜熱放出の有無が差の主因。", "不正解。温度の高低は直接の理由ではない。", "不正解。圧力差が主因ではない。", "不正解。乾燥空気は水蒸気が少ない。"],
    basic_terms: "断熱減率：上昇気塊の温度低下率、潜熱：相変化に伴う熱"
  }),
  q({
    domain: "地学",
    subdomain: "地球化学",
    difficulty_initial: 400,
    cognitive_type: "比較・分類",
    question_text: "放射性同位体年代測定で、数万年以内の有機試料の年代決定に最も適した核種の組合せはどれか。",
    choices: ["ウラン-鉛法", "カリウム-アルゴン法", "炭素14法", "ルビジウム-ストロンチウム法"],
    correct_choice_index: 2,
    short_explanation: "¹⁴C の半減期は約5730年で数万年スケールに適する。",
    detailed_explanation: "¹⁴C 法は有機物・考古試料に用いる。U-Pb や K-Ar は地質年代（百万年以上）向け。",
    learning_objective: "年代測定法と対象年代の適合を判断できる",
    common_misconception: "どの年代測定法も同じ年代範囲に使えると考える",
    distractor_rationales: ["不正解。数十億年スケール向け。", "不正解。主に百万年以上。", "正解。数万年スケールの有機試料に適する。", "不正解。古い岩石向け。"],
    basic_terms: "炭素14法：¹⁴C 崩壊を用いた年代測定、半減期：親核種が半分に減る時間"
  }),
  q({
    domain: "地学",
    subdomain: "海洋学",
    difficulty_initial: 400,
    cognitive_type: "原理・因果",
    question_text: "エルニーニョ現象が発生したとき、太平洋赤道域の東部で起こりやすい変化として正しいものはどれか。",
    choices: ["海面水温の上昇と対流活動の活発化", "海面水温の低下と強い上昇流", "塩分濃度の急激な上昇のみ", "海流の完全停止"],
    correct_choice_index: 0,
    short_explanation: "エルニーニョでは東太平洋の海面水温が上昇し、通常の冷たい上昇流が弱まる。",
    detailed_explanation: "貿易風の弱まりにより暖水が東進し、ペルー沖の漁場にも影響する。",
    learning_objective: "エルニーニョの海洋・大気変化を説明できる",
    common_misconception: "エルニーニョで東太平洋が冷えると考える",
    distractor_rationales: ["正解。東太平洋の暖化が特徴。", "不正解。ラニーニャに近い変化。", "不正解。塩分だけの変化ではない。", "不正解。海流は弱まるが停止しない。"],
    basic_terms: "エルニーニョ：赤道太平洋の異常暖事件、上昇流：深層水の上昇"
  }),
  q({
    domain: "地学",
    subdomain: "地震学",
    difficulty_initial: 400,
    cognitive_type: "誤解・境界",
    question_text: "地震波のうち、液体層（外核）を通過できない波の種類はどれか。",
    choices: ["P波（縦波）", "S波（横波）", "表面波", "どちらも通過できる"],
    correct_choice_index: 1,
    short_explanation: "S波は横波のため剪断応力を伝えられず、液体を通過しない。",
    detailed_explanation: "P波は縦波で液体も通過する。S波のシャドウゾーンは外核が液体である証拠。",
    learning_objective: "P波とS波の性質差と地球内部構造の推定を説明できる",
    common_misconception: "すべての地震波が地球内部を通過すると考える",
    distractor_rationales: ["不正解。P波は液体を通過する。", "正解。横波は剪断を伝えられず液体不通過。", "不正解。表面波は地表近くを伝播。", "不正解。S波は外核を通過しない。"],
    basic_terms: "P波：縦波・初動波、S波：横波・剪断波"
  }),
  q({
    domain: "地学",
    subdomain: "地球物理学",
    difficulty_initial: 500,
    cognitive_type: "基本的な適用",
    question_text: "地磁気の北偏角（偏角）が定義される関係として正しいものはどれか。",
    choices: ["磁北と真北のなす角", "磁気傾角と水平面のなす角", "重力と地磁気のなす角", "黄道と赤道のなす角"],
    correct_choice_index: 0,
    short_explanation: "偏角は水平面内で磁北と真北（地理北）のなす角。",
    detailed_explanation: "偏角は地域・時代により変化する。傾角は磁気と水平面のなす角で別概念。",
    learning_objective: "地磁気の偏角と傾角を区別できる",
    common_misconception: "偏角と傾角を混同する",
    distractor_rationales: ["正解。磁北と真北の水平角。", "不正解。これは磁気傾角の定義。", "不正解。無関係な組合せ。", "不正解。黄道傾斜角の話。"],
    basic_terms: "偏角：磁北と真北の水平角、傾角：地磁気と水平面のなす角"
  }),
  q({
    domain: "地学",
    subdomain: "気象学",
    difficulty_initial: 600,
    cognitive_type: "原理・因果",
    question_text: "北半球で気圧の低い領域に向かって吹く風が右に偏れる主な原因はどれか。",
    choices: ["重力", "コリオリ力", "表面摩擦のみ", "大気の圧縮"],
    correct_choice_index: 1,
    short_explanation: "地球の自転によるコリオリ力が北半球で右偏（フェルミール）を生む。",
    detailed_explanation: "コリオリ力は自転座標系での見かけの力。北半球では低気圧周辺で反時計回りの風。",
    learning_objective: "コリオリ力と風の偏りの関係を説明できる",
    common_misconception: "風は単純に気圧勾配方向に吹くと考える",
    distractor_rationales: ["不正解。重力は鉛直方向が主。", "正解。自転による見かけの偏向力。", "不正解。摩擦は速度減衰が主で偏りの主因ではない。", "不正解。圧縮は直接の偏り原因ではない。"],
    basic_terms: "コリオリ力：自転系で見かけの偏向力、気圧勾配力：高低気圧間の圧力差による力"
  }),
  q({
    domain: "地学",
    subdomain: "地球化学",
    difficulty_initial: 600,
    cognitive_type: "基本的な適用",
    question_text: "放射性同位体年代測定で、親核種の半減期が未知の試料年代に対して長すぎる場合に起こりやすい問題はどれか。",
    choices: ["半減期が短くなって測定が不可能になる", "親核種の減衰がほとんど進んでおらず年代を区別しにくい", "子核種が親核種より先に消える", "試料が直ちに全核種に崩壊する"],
    correct_choice_index: 1,
    short_explanation: "半減期が試料年代に比べ長いと、残存親核種の差が小さく年代解像度が低下する。",
    detailed_explanation: "例：数万年の試料に半減期45億年の U-Pb は不適。¹⁴C は数万年以内に適する。",
    learning_objective: "放射性年代測定で半減期と測定対象年代の適合を判断できる",
    common_misconception: "半減期が長いほど常に高精度だと誤解する",
    distractor_rationales: ["不正解。半減期は核種の固有性質。", "正解。減衰が少なく統計的区別が困難。", "不正解。子核種は親の崩壊で増加する。", "不正解。崩壊は確率的で即時全崩壊はしない。"],
    basic_terms: "半減期：親核種が半分に減る時間、放射性年代測定：崩壊系列を用いた年代決定"
  }),
  q({
    domain: "地学",
    subdomain: "地質学",
    difficulty_initial: 600,
    cognitive_type: "比較・分類",
    question_text: "変成岩のファシーズ（変相）が進むと一般に見られる変化として最も適切なものはどれか。",
    choices: ["温度・圧力上昇に伴い安定な鉱物組合せが変わる", "すべての岩石が堆積岩になる", "石英だけが残り他の鉱物は消失する", "変成作用は温度のみで決まる"],
    correct_choice_index: 0,
    short_explanation: "変相系列は P-T 条件に応じて安定鉱物組合せが変化する。",
    detailed_explanation: "ブルーシスト・緑片岩・角閃岩・グラニュライト相など、条件に応じた鉱物変化が起こる。",
    learning_objective: "変成相と鉱物組合せの関係を説明できる",
    common_misconception: "変成岩はすべて同じ鉱物組成だと考える",
    distractor_rationales: ["正解。P-T 条件で安定相が変化。", "不正解。変成岩は変成由来。", "不正解。多様な鉱物が安定化する。", "不正解。圧力も重要な変数。"],
    basic_terms: "変成相：変成作用の P-T 条件の範囲、ファシーズ：変相の英語表記"
  }),
  q({
    domain: "地学",
    subdomain: "地震学",
    difficulty_initial: 700,
    cognitive_type: "原理・因果",
    question_text: "スロー地震（スロースリップ事象）が通常の地震と異なる主な特徴として正しいものはどれか。",
    choices: ["非常に短時間で高周波の振動を放出する", "断層滑りが数週間から数年かけてゆっくり進行する", "地表にのみ発生し深部では起こらない", "P波のみが観測される"],
    correct_choice_index: 1,
    short_explanation: "スロー地震は低速・長時間の断層滑りで、通常地震より低周波エネルギーが主。",
    detailed_explanation: "スロースリップは深部断層やプレート境界で観測され、通常地震の前触れや連動に関与する。",
    learning_objective: "通常地震とスロー地震の時間・周波数特性の違いを説明できる",
    common_misconception: "すべての断層運動が高速で短時間だと考える",
    distractor_rationales: ["不正解。通常地震の特徴。", "正解。長時間スケールのゆっくりした滑り。", "不正解。深部でも観測される。", "不正解。低周波成分が主。"],
    basic_terms: "スロー地震：低速長時間の断層滑り、スロースリップ：ゆっくりしたすべり運動"
  }),
  q({
    domain: "地学",
    subdomain: "地球物理学",
    difficulty_initial: 700,
    cognitive_type: "基本的な適用",
    question_text: "マントル対流がプレート駆動力の一つとされる根拠として最も適切なものはどれか。",
    choices: ["マントルの温度・密度差による上昇流・下降流が岩石圏プレートに引っ張り力を与える", "マントルは完全に固体で対流しない", "対流は地殻の風化のみで起こる", "プレート運動は月の引力だけで決まる"],
    correct_choice_index: 0,
    short_explanation: "マントル対流による牽引・押し込みがプレート運動を駆動する。",
    detailed_explanation: "ラジオ活性崩壊熱によるマントル対流が、スラブプル・リッジプッシュなどと関連する。",
    learning_objective: "マントル対流とプレートテクトニクスの関係を説明できる",
    common_misconception: "プレートは地表の力だけで動くと考える",
    distractor_rationales: ["正解。マントル対流がプレートに力を伝える。", "不正解。マントルは高温で対流する。", "不正解。風化はプレート駆動力ではない。", "不正解。月の引力は潮汐の主因。"],
    basic_terms: "マントル対流：マントル内の熱対流、スラブプル：沈み込みプレートによる牽引力"
  }),
  q({
    domain: "地学",
    subdomain: "地球化学",
    difficulty_initial: 800,
    cognitive_type: "原理・因果",
    question_text: "安定同位体（例：δ¹⁸O）を用いた古気候再構築で、海洋プランクトンの殻からδ¹⁸Oが高い値を示すことが氷期と結びつく主な理由はどれか。",
    choices: ["氷期には軽い同位素が氷床に蓄積し海水が重くなるため", "氷期には全同位素が均等に増えるため", "プランクトンは氷期に酸素を消費するため", "δ¹⁸O は温度と無関係だから"],
    correct_choice_index: 0,
    short_explanation: "氷期に¹⁶O が氷床に優先的に固定され、残った海水・生物殻は δ¹⁸O が高くなる。",
    detailed_explanation: "同位素分別により軽い酸素が氷に移り、海水の δ¹⁸O が上昇。温度効果と分別効果を区別して解釈する。",
    learning_objective: "酸素同位体パレオ温度計の原理を説明できる",
    common_misconception: "δ¹⁸O は温度だけで決まると単純化する",
    distractor_rationales: ["正解。氷床への¹⁶O 固定が主因の一つ。", "不正解。同位素は分別される。", "不正解。酸素消費の話ではない。", "不正解。温度と分別の両方に依存。"],
    basic_terms: "δ¹⁸O：酸素安定同位体比の偏差、同位素分別：質量差による分配の違い"
  })
];
