import { q } from "../lib/batch50-helpers.mjs";

export const engineeringGap = [
  q({
    domain: "工学",
    subdomain: "機械",
    difficulty_initial: 100,
    cognitive_type: "用語・定義",
    question_text: "力のSI単位として正しいものはどれか。",
    choices: ["ニュートン (N)", "ジュール (J)", "パスカル (Pa)", "ワット (W)"],
    correct_choice_index: 0,
    short_explanation: "力のSI単位はニュートン（N = kg·m/s²）。",
    detailed_explanation: "SIでは力はニュートン。ジュールはエネルギー、パスカルは圧力、ワットは仕事率の単位。",
    learning_objective: "SIの基本単位で力・エネルギー・圧力・仕事率を区別できる",
    common_misconception: "ジュールやワットも力の単位だと混同する",
    distractor_rationales: ["正解。F=ma から定義される力の単位。", "不正解。エネルギー・仕事の単位（N·m）。", "不正解。圧力の単位（N/m²）。", "不正解。仕事率の単位（J/s）。"],
    basic_terms: "ニュートン：力のSI単位、ジュール：エネルギーの単位"
  }),
  q({
    domain: "工学",
    subdomain: "電気",
    difficulty_initial: 200,
    cognitive_type: "原理・因果",
    question_text: "直列回路で電流がどの素子でも同じ値になる主な理由はどれか。",
    choices: ["電荷の保存により一つの経路を流れる電荷量が同じだから", "各素子の抵抗が同じだから", "電圧がすべての素子で等しいから", "電源の極性が変わるから"],
    correct_choice_index: 0,
    short_explanation: "直列では電流の経路が一つなので、どの点でも同じ電流が流れる。",
    detailed_explanation: "電荷保存則より直列回路の任意の断面を通る電流は等しい。電圧は素子ごとに分配される。",
    learning_objective: "直列回路の電流・電圧の関係を説明できる",
    common_misconception: "直列でも電流が分かれると考える",
    distractor_rationales: ["正解。単一経路の電荷保存。", "不正解。抵抗は一般に異なる。", "不正解。直列では電圧は分配される。", "不正解。極性は電流等価性の理由ではない。"],
    basic_terms: "直列回路：一つの経路に素子がつながる回路、電流：単位時間の電荷の流れ"
  }),
  q({
    domain: "工学",
    subdomain: "材料",
    difficulty_initial: 200,
    cognitive_type: "比較・分類",
    question_text: "鉄とアルミニウムを比較したとき、同じ体積で質量が大きいのはどちらか。",
    choices: ["鉄", "アルミニウム", "同じ", "温度で決まる"],
    correct_choice_index: 0,
    short_explanation: "鉄の密度は約7.9 g/cm³、アルミは約2.7 g/cm³で鉄の方が重い。",
    detailed_explanation: "密度 = 質量/体積。同体積なら密度が大きい鉄の方が質量が大きい。",
    learning_objective: "密度の概念を用いて材料の質量を比較できる",
    common_misconception: "金属はすべて同じくらい重いと考える",
    distractor_rationales: ["正解。鉄の密度が大きい。", "不正解。アルミは軽金属。", "不正解。密度が異なる。", "不正解。常温では材料固有の密度で決まる。"],
    basic_terms: "密度：単位体積あたりの質量、軽金属：密度の小さい金属"
  }),
  q({
    domain: "工学",
    subdomain: "土木",
    difficulty_initial: 200,
    cognitive_type: "基本的な適用",
    question_text: "河川の堤防が洪水時に水の圧力を受けるとき、水深が2倍になると静水圧はおよそ何倍になるか。",
    choices: ["2倍", "4倍", "変わらない", "√2倍"],
    correct_choice_index: 0,
    short_explanation: "静水圧 p = ρgh より水深 h に比例する。",
    detailed_explanation: "液体の静水圧は深度に比例。水深2倍で圧力も約2倍（密度・重力加速度一定とする）。",
    learning_objective: "静水圧と水深の関係を説明できる",
    common_misconception: "圧力は水深の2乗に比例すると誤解する",
    distractor_rationales: ["正解。p ∝ h。", "不正解。2乗関係ではない。", "不正解。水深で変化する。", "不正解。平方根関係ではない。"],
    basic_terms: "静水圧：静止流体の圧力、水深：水面からの垂直距離"
  }),
  q({
    domain: "工学",
    subdomain: "熱工学",
    difficulty_initial: 200,
    cognitive_type: "用語・定義",
    question_text: "熱エンジンが熱源から吸収した熱量のうち、仕事として取り出せる割合を表す量はどれか。",
    choices: ["熱効率", "比熱", "熱伝導率", "エントロピー"],
    correct_choice_index: 0,
    short_explanation: "熱効率 η = 仕事/吸熱量。",
    detailed_explanation: "熱機関の性能指標は熱効率。カーノー効率が理論上限。比熱・熱伝導率は別の物性。",
    learning_objective: "熱効率の定義を説明できる",
    common_misconception: "吸収した熱をすべて仕事にできると考える",
    distractor_rationales: ["正解。仕事/吸熱の比。", "不正解。温度上昇に必要な熱量の物性。", "不正解。熱の伝わりやすさ。", "不正解。熱力学状態量。"],
    basic_terms: "熱効率：熱エネルギーを仕事に変換する効率、熱機関：熱で仕事をする装置"
  }),
  q({
    domain: "工学",
    subdomain: "制御",
    difficulty_initial: 300,
    cognitive_type: "原理・因果",
    question_text: "PID制御において、積分（I）項の主な役割として最も適切なものはどれか。",
    choices: ["定常偏差（オフセット）を除去する", "応答を高速化するだけ", "高周波ノイズを増幅する", "系の不安定化を目的とする"],
    correct_choice_index: 0,
    short_explanation: "積分項は過去の偏差を蓄積し定常偏差をゼロに近づける。",
    detailed_explanation: "P項は比例、I項は定常偏差除去、D項は微分で過渡応答改善。",
    learning_objective: "PID制御各項の役割を説明できる",
    common_misconception: "I項は応答速度だけを上げると考える",
    distractor_rationales: ["正解。定常偏差の除去が主目的。", "不正解。高速化はP・Dの寄与も大きい。", "不正解。D項がノイズに敏感になりやすい。", "不正解。制御の目的は安定化。"],
    basic_terms: "PID制御：比例・積分・微分制御、定常偏差：目標値と実測値の定常的な差"
  }),
  q({
    domain: "工学",
    subdomain: "流体力学",
    difficulty_initial: 300,
    cognitive_type: "基本的な適用",
    question_text: "管内の流体で、断面積が半分になり流速が2倍になったとき、ベルヌーイの定理から静圧はどうなるか（高さ変化なし）。",
    choices: ["増加する", "減少する", "変わらない", "ゼロになる"],
    correct_choice_index: 1,
    short_explanation: "流速増加に伴い運動エネルギーが増え、静圧は低下する。",
    detailed_explanation: "p + ½ρv² = 一定（水平管）。v が2倍なら v² は4倍、静圧 p は低下。",
    learning_objective: "ベルヌーイの定理を用いて圧力変化を予測できる",
    common_misconception: "流速が上がると圧力も上がると考える",
    distractor_rationales: ["不正解。ベルヌーイでは逆の関係。", "正解。流速増で静圧低下。", "不正解。エネルギー保存で変化する。", "不正解。ゼロにはならない。"],
    basic_terms: "ベルヌーイの定理：流れのエネルギー保存、静圧：流体の圧力"
  }),
  q({
    domain: "工学",
    subdomain: "材料力学",
    difficulty_initial: 300,
    cognitive_type: "用語・定義",
    question_text: "材料に外力を加えたとき、単位断面積あたりの内力を表す量はどれか。",
    choices: ["応力", "ひずみ", "弾性係数", "トルク"],
    correct_choice_index: 0,
    short_explanation: "応力 σ = 力/断面積。",
    detailed_explanation: "応力は内力の強さ。ひずみは変形の割合、弾性係数は応力とひずみの比。",
    learning_objective: "応力・ひずみ・弾性係数を区別できる",
    common_misconception: "応力とひずみを同一視する",
    distractor_rationales: ["正解。力/断面積の内力。", "不正解。変形の相対量。", "不正解。応力/ひずみ（ヤング率等）。", "不正解。回転を起こす力のモーメント。"],
    basic_terms: "応力：単位面積の内力、ひずみ：変形の相対量"
  }),
  q({
    domain: "工学",
    subdomain: "構造工学",
    difficulty_initial: 300,
    cognitive_type: "比較・分類",
    question_text: "単純支持はりの中央に集中荷重を加えたとき、最大曲げモーメントが生じる位置はどれか。",
    choices: ["支点", "中央", "自由端", "どこでも同じ"],
    correct_choice_index: 1,
    short_explanation: "単純梁の中央集中荷重では中央で曲げモーメントが最大。",
    detailed_explanation: "両端支持・中央荷重の場合 M_max = PL/4 が中央で生じる。",
    learning_objective: "単純梁の曲げモーメント分布を理解できる",
    common_misconception: "支点で常に最大モーメントだと考える",
    distractor_rationales: ["不正解。支点ではせん断力が最大だが曲げは小さい。", "正解。中央で曲げモーメント最大。", "不正解。単純支持には自由端がない。", "不正解。位置により異なる。"],
    basic_terms: "曲げモーメント：断面を曲げる力のモーメント、単純支持：両端がピン支持のはり"
  }),
  q({
    domain: "工学",
    subdomain: "電気",
    difficulty_initial: 400,
    cognitive_type: "基本的な適用",
    question_text: "交流回路で、電圧の実効値（RMS）が100 V のとき、最大値（ピーク値）はおよそいくらか。",
    choices: ["100 V", "141 V", "200 V", "70.7 V"],
    correct_choice_index: 1,
    short_explanation: "正弦波の実効値 V_rms = V_peak/√2 より V_peak ≈ 141 V。",
    detailed_explanation: "100 V の実効値は最大値約141 V。コンセントの100 V は実効値。",
    learning_objective: "交流の実効値と最大値の関係を計算できる",
    common_misconception: "実効値と最大値を同じと考える",
    distractor_rationales: ["不正解。実効値そのもの。", "正解。100×√2 ≈ 141 V。", "不正解。2倍は過大。", "不正解。実効値/√2 は最大値ではない。"],
    basic_terms: "実効値：交流を直流と同等の仕事に換算した値、ピーク値：最大振幅"
  }),
  q({
    domain: "工学",
    subdomain: "機械",
    difficulty_initial: 400,
    cognitive_type: "原理・因果",
    question_text: "歯車ペアで大きい歯車の回転速度が小さい歯車より遅い主な理由はどれか。",
    choices: ["大きい歯車の歯数が多く、同じ接線速度で回転数が少なくなるから", "大きい歯車は常に摩擦が大きいから", "小さい歯車だけが動力を受けるから", "歯車の大きさは回転数と無関係だから"],
    correct_choice_index: 0,
    short_explanation: "接線速度 v = ωr が等しいとき、半径（歯数）が大きいほど角速度 ω は小さい。",
    detailed_explanation: "歯数比によりトルクと回転数がトレードオフ。大歯車は低速・大トルク側。",
    learning_objective: "歯車比と回転数・トルクの関係を説明できる",
    common_misconception: "歯車の大きさは回転に影響しないと考える",
    distractor_rationales: ["正解。歯数（半径）と回転数の反比例。", "不正解。摩擦は損失要因だが主因ではない。", "不正解。両方が噛み合って動力伝達。", "不正解。歯数比で回転数は変わる。"],
    basic_terms: "歯車比：歯数の比による速度比、接線速度：歯車接点での速度"
  }),
  q({
    domain: "工学",
    subdomain: "熱工学",
    difficulty_initial: 400,
    cognitive_type: "比較・分類",
    question_text: "冷凍サイクルにおいて、蒸発器で起こる主な熱の移動の向きとして正しいものはどれか。",
    choices: ["冷媒から周囲へ熱を放出", "周囲から冷媒へ熱を吸収", "冷媒内部だけで熱が循環", "熱の移動は起こらない"],
    correct_choice_index: 1,
    short_explanation: "蒸発器では低温低圧の冷媒が蒸発し、周囲から熱を吸収する。",
    detailed_explanation: "蒸発器＝吸熱、凝縮器＝放熱。冷凍機は蒸発器で冷却したい空間から熱を奪う。",
    learning_objective: "冷凍サイクルの各器の熱の流れを説明できる",
    common_misconception: "蒸発器で熱を放出すると考える（凝縮器と混同）",
    distractor_rationales: ["不正解。凝縮器の役割。", "正解。蒸発器は吸熱。", "不正解。外部との熱交換がある。", "不正解。蒸発は潜熱吸収を伴う。"],
    basic_terms: "蒸発器：冷媒が蒸発して吸熱する熱交換器、冷媒：熱を運ぶ流体"
  }),
  q({
    domain: "工学",
    subdomain: "情報通信",
    difficulty_initial: 400,
    cognitive_type: "用語・定義",
    question_text: "デジタル通信で、1秒間に伝送されるビット数を表す量はどれか。",
    choices: ["ビットレート", "変調指数", "帯域幅", "信号対雑音比"],
    correct_choice_index: 0,
    short_explanation: "ビットレート（bps）は単位時間あたりのビット数。",
    detailed_explanation: "bps = bits per second。帯域幅は周波数幅、SNR は信号品質の指標。",
    learning_objective: "デジタル通信の基本指標を区別できる",
    common_misconception: "帯域幅とビットレートを同一視する",
    distractor_rationales: ["正解。単位時間のビット数。", "不正解。変調の深さの指標。", "不正解。周波数の幅。", "不正解。信号と雑音の比。"],
    basic_terms: "ビットレート：情報伝送速度、帯域幅：信号が占める周波数範囲"
  }),
  q({
    domain: "工学",
    subdomain: "材料",
    difficulty_initial: 500,
    cognitive_type: "原理・因果",
    question_text: "金属の降伏後に加工硬化が起こる主な機構として最も適切なものはどれか。",
    choices: ["転位の増殖と相互作用により変形抵抗が増加する", "結晶粒が即座に消失する", "原子がすべて気化する", "弾性変形のみが続く"],
    correct_choice_index: 0,
    short_explanation: "塑性変形で転位が増え絡み合い、さらなる変形に抵抗が増す。",
    detailed_explanation: "加工硬化（応力硬化）は転位密度の増加が主因。再結晶で軟化も可能。",
    learning_objective: "塑性変形と加工硬化の機構を説明できる",
    common_misconception: "降伏後は常に強度が下がると考える",
    distractor_rationales: ["正解。転位による硬化機構。", "不正解。粒は再結晶で変化するが即消失ではない。", "不正解。気化は起こらない。", "不正解。降伏後は塑性変形。"],
    basic_terms: "加工硬化：塑性変形後の強度上昇、転位：結晶内の線状欠陥"
  }),
  q({
    domain: "工学",
    subdomain: "制御",
    difficulty_initial: 600,
    cognitive_type: "基本的な適用",
    question_text: "フィードバック制御系の閉ループ伝達関数で、ナイキスト安定判据が適用する対象として正しいものはどれか。",
    choices: ["開ループ伝達関数の周波数応答", "センサの物理寸法", "モータの質量のみ", "電源電圧の直流値のみ"],
    correct_choice_index: 0,
    short_explanation: "ナイキスト判据は開ループ伝達関数 L(jω) の周波数応答から閉ループ安定性を判定する。",
    detailed_explanation: "L(jω) の -1 点に対する周回数と周回方向から安定性を判断。",
    learning_objective: "ナイキスト判据の適用対象を説明できる",
    common_misconception: "閉ループ伝達関数を直接プロットする必要があると考える",
    distractor_rationales: ["正解。開ループ伝達関数の周波数応答。", "不正解。幾何寸法は無関係。", "不正解。パラメータ一つでは判据は成立しない。", "不正解。周波数応答解析が必要。"],
    basic_terms: "ナイキスト判据：開ループ周波数応答による安定性判定、開ループ伝達関数：帰還路を含む伝達関数"
  }),
  q({
    domain: "工学",
    subdomain: "流体力学",
    difficulty_initial: 600,
    cognitive_type: "原理・因果",
    question_text: "レイノルズ数が臨界値を超えて乱流になると、管摩擦損失が層流より大きくなる主な理由はどれか。",
    choices: ["乱流では速度分布の勾配が壁近傍で大きくなりせん断応力が増加する", "乱流では密度が2倍になる", "乱流では粘性がゼロになる", "乱流では流速がゼロになる"],
    correct_choice_index: 0,
    short_explanation: "乱流の脈動により壁近傍の速度勾配・せん断応力が増大し摩擦損失が増える。",
    detailed_explanation: "ダルシー・ワイスバッハ式の摩擦係数 f は乱流で Re に依存し層流より大きくなる。",
    learning_objective: "レイノルズ数と流れ状態・摩擦損失の関係を説明できる",
    common_misconception: "乱流でも摩擦損失は層流と同じだと考える",
    distractor_rationales: ["正解。壁近傍勾配増大が主因。", "不正解。密度は変わらない。", "不正解。粘性はある。", "不正解。平均流速はゼロではない。"],
    basic_terms: "レイノルズ数：慣性力と粘性力の比、乱流：不規則な脈動を伴う流れ"
  }),
  q({
    domain: "工学",
    subdomain: "構造工学",
    difficulty_initial: 700,
    cognitive_type: "基本的な適用",
    question_text: "鉄骨ラーメン構造の弾塑性解析で、塑性ヒンジが形成されるとその断面の曲げ剛性が実質的にゼロに近づく理由として最も適切なものはどれか。",
    choices: ["降伏により追加の曲げモーメントを負担できず変形だけが進む", "鉄が液体になる", "外力がゼロになる", "弾性係数が無限大になる"],
    correct_choice_index: 0,
    short_explanation: "塑性ヒンジでは M = M_y で飽和し、剛性が低下して回転変形が集中する。",
    detailed_explanation: "塑性解析ではヒンジ部で曲げ剛性をゼロと近似し、崩壊機構を求める。",
    learning_objective: "塑性ヒンジの概念と構造解析への応用を説明できる",
    common_misconception: "降伏後も無限にモーメントが増えると考える",
    distractor_rationales: ["正解。降伏モーメントで飽和し剛性低下。", "不正解。相変化ではない。", "不正解。外力は継続する。", "不正解。剛性は低下する。"],
    basic_terms: "塑性ヒンジ：降伏により回転変形が集中する断面、降伏モーメント：塑性化開始の曲げモーメント"
  }),
  q({
    domain: "工学",
    subdomain: "材料力学",
    difficulty_initial: 700,
    cognitive_type: "原理・因果",
    question_text: "疲労破壊が繰り返し応力の最大値が降伏応力以下でも起こりうる主な理由はどれか。",
    choices: ["微細なき裂が繰り返し荷重で進展し、有効断面が減少して破壊する", "材料が毎回完全に再生する", "一度も塑性変形が起きない", "静的強度だけで寿命が決まる"],
    correct_choice_index: 0,
    short_explanation: "疲労はき裂の発生・進展による破壊で、静強度以下の繰返し応力でも起こる。",
    detailed_explanation: "S-N 線図で繰返し応力と寿命の関係。き裂進展は局部で応力集中を生む。",
    learning_objective: "疲労破壊の機構を説明できる",
    common_misconception: "降伏応力以下なら永久に安全だと考える",
    distractor_rationales: ["正解。き裂進展による破壊機構。", "不正解。累積損傷が進む。", "不正解。局部では塑性化も起こる。", "不正解。繰返し荷重が寿命を支配。"],
    basic_terms: "疲労破壊：繰返し荷重による破壊、S-N 線図：応力振幅と寿命の関係"
  }),
  q({
    domain: "工学",
    subdomain: "電気",
    difficulty_initial: 800,
    cognitive_type: "原理・因果",
    question_text: "MOSFETの短チャネル効果で、しきい値電圧がチャネル長の短縮とともに低下する主な物理的原因はどれか。",
    choices: ["ソース・ドレインの耗尽層がチャネル領域に侵入し電荷制御が弱まる", "ゲート酸化膜が厚くなる", "チャネル長が無限大になる", "ドープ濃度がゼロになる"],
    correct_choice_index: 0,
    short_explanation: "短チャネルでは2次元電荷共有により有効しきい値が低下する。",
    detailed_explanation: "DIBL（ドレイン誘起バリア低下）なども短チャネル効果の一つ。",
    learning_objective: "MOSFETの短チャネル効果を説明できる",
    common_misconception: "しきい値は長さと無関係だと考える",
    distractor_rationales: ["正解。耗尽層侵入による電荷共有。", "不正解。酸化膜厚は製造パラメータ。", "不正解。短チャネルは長さが短い。", "不正解。ドープはある。"],
    basic_terms: "短チャネル効果：チャネル長短縮による特性変化、しきい値電圧：反転開始のゲート電圧"
  }),
  q({
    domain: "工学",
    subdomain: "熱工学",
    difficulty_initial: 800,
    cognitive_type: "基本的な適用",
    question_text: "二流体熱交換器の対数平均温度差（LMTD）法が適用できる前提として最も適切なものはどれか。",
    choices: ["両流体の温度が流れ方向に沿って単調に変化し、全体として対向流または並流の一定パターンである", "流体の温度が途中で逆転する", "熱交換面積がゼロである", "伝熱係数が位置で激しく変動し一定でない"],
    correct_choice_index: 0,
    short_explanation: "LMTD法は定常状態・一定U・単調温度変化の対向流/並流に適用。",
    detailed_explanation: "ΔT_m = (ΔT₁−ΔT₂)/ln(ΔT₁/ΔT₂)。複雑な流路では修正係数Fを用いる。",
    learning_objective: "LMTD法の適用条件を説明できる",
    common_misconception: "任意の熱交換器に算術平均温度差でよいと考える",
    distractor_rationales: ["正解。LMTDの標準適用条件。", "不正解。温度逆転では単純LMTDは不適。", "不正解。面積ゼロでは熱交換しない。", "不正解。U一定が前提の一つ。"],
    basic_terms: "LMTD：対数平均温度差、熱交換器：二流体間で熱を交換する装置"
  })
];
