import { q } from "../lib/batch50-helpers.mjs";

export const csGap = [
  // L100 ×2
  q({
    domain: "情報・計算機科学",
    subdomain: "ハードウェア",
    difficulty_initial: 100,
    cognitive_type: "用語・定義",
    question_text: "コンピュータが文字や数値などのデータを記憶しておく部品はどれか。",
    choices: ["CPU", "メモリ", "モニター", "キーボード"],
    correct_choice_index: 1,
    short_explanation: "メモリ（主記憶装置）は処理中のデータやプログラムを一時的に保持する。",
    detailed_explanation: "CPU は演算・制御、メモリはデータ保持、モニターとキーボードは入出力装置である。",
    learning_objective: "コンピュータの基本構成要素の役割を区別できる",
    common_misconception: "データ保存はすべてハードディスクが担うと考える",
    distractor_rationales: ["不正解。演算と制御を行う。", "正解。主記憶としてデータを保持する。", "不正解。出力装置。", "不正解。入力装置。"],
    basic_terms: "CPU：中央処理装置、メモリ：主記憶装置"
  }),
  q({
    domain: "情報・計算機科学",
    subdomain: "情報表現",
    difficulty_initial: 100,
    cognitive_type: "原理・因果",
    question_text: "コンピュータ内部で情報を表す最小単位として正しいものはどれか。",
    choices: ["バイト", "ビット", "ワード", "ピクセル"],
    correct_choice_index: 1,
    short_explanation: "ビット（0 または 1）が情報表現の最小単位である。",
    detailed_explanation: "8 ビットで 1 バイト、複数バイトで数値や文字を表現する。ピクセルは画像の画素単位。",
    learning_objective: "デジタル情報の基本単位を説明できる",
    common_misconception: "バイトが最小単位だと誤解する",
    distractor_rationales: ["不正解。8 ビットのまとまり。", "正解。0/1 の最小単位。", "不正解。処理単位の名称。", "不正解。画像の画素。"],
    basic_terms: "ビット：二進の1桁、バイト：8ビットのまとまり"
  }),
  // L200 ×4
  q({
    domain: "情報・計算機科学",
    subdomain: "プログラミング",
    difficulty_initial: 200,
    cognitive_type: "用語・定義",
    question_text: "同じ処理を条件が満たされるまで繰り返し実行する制御構造はどれか。",
    choices: ["分岐", "ループ", "代入", "コメント"],
    correct_choice_index: 1,
    short_explanation: "ループ（反復）は条件を満たす間、処理を繰り返す。",
    detailed_explanation: "for 文や while 文はループの代表例。分岐は条件による経路選択、代入は値の格納。",
    learning_objective: "基本的な制御構造を区別できる",
    common_misconception: "ループと再帰を同一視する",
    distractor_rationales: ["不正解。if 等による経路選択。", "正解。繰り返し実行の構造。", "不正解。変数への値の代入。", "不正解。プログラムの説明文。"],
    basic_terms: "ループ：反復構造、分岐：条件分岐"
  }),
  q({
    domain: "情報・計算機科学",
    subdomain: "ネットワーク",
    difficulty_initial: 200,
    cognitive_type: "基本的な適用",
    question_text: "インターネット上の Web ページを特定するための文字列を何というか。",
    choices: ["IP アドレス", "URL", "MAC アドレス", "DNS レコード"],
    correct_choice_index: 1,
    short_explanation: "URL（Uniform Resource Locator）は Web 上の資源の場所を示す。",
    detailed_explanation: "URL はプロトコル・ホスト名・パス等を含む。IP アドレスは機器の番号、MAC は物理アドレス。",
    learning_objective: "Web 閲覧で用いる識別子を説明できる",
    common_misconception: "URL と IP アドレスを混同する",
    distractor_rationales: ["不正解。機器のネットワーク番号。", "正解。資源の場所を示す文字列。", "不正解。NIC の物理アドレス。", "不正解。名前解決のデータ。"],
    basic_terms: "URL：資源の場所を示す文字列、IP アドレス：ネットワーク上の機器番号"
  }),
  q({
    domain: "情報・計算機科学",
    subdomain: "暗号",
    difficulty_initial: 200,
    cognitive_type: "比較・分類",
    question_text: "暗号化と復号に同じ鍵を用いる暗号方式を何というか。",
    choices: ["公開鍵暗号", "共通鍵暗号", "ハッシュ関数", "デジタル署名のみ"],
    correct_choice_index: 1,
    short_explanation: "共通鍵（対称鍵）暗号は送受信者が同一の秘密鍵を共有する。",
    detailed_explanation: "AES 等が代表例。公開鍵暗号は異なる鍵ペアを用い、ハッシュは一方向変換。",
    learning_objective: "対称鍵暗号の基本特徴を説明できる",
    common_misconception: "すべての暗号が公開鍵方式だと誤解する",
    distractor_rationales: ["不正解。異なる公開鍵と秘密鍵を用いる。", "正解。同一鍵で暗号化・復号。", "不正解。一方向の要約関数。", "不正解。署名は認証の仕組み。"],
    basic_terms: "共通鍵暗号：同一鍵を用いる暗号、公開鍵暗号：鍵ペアを用いる暗号"
  }),
  q({
    domain: "情報・計算機科学",
    subdomain: "データ構造",
    difficulty_initial: 200,
    cognitive_type: "原理・因果",
    question_text: "配列と連結リストを比較したとき、配列の典型的な利点として正しいものはどれか。",
    choices: ["要素の挿入が常に O(1)", "任意の位置へのランダムアクセスが速い", "使用メモリが常に少ない", "要素数に上限がない"],
    correct_choice_index: 1,
    short_explanation: "配列はインデックスで O(1) のランダムアクセスが可能。",
    detailed_explanation: "連結リストは挿入・削除に有利だが、i 番目要素へのアクセスは O(n)。配列は連続領域に配置される。",
    learning_objective: "配列と連結リストの特性を比較できる",
    common_misconception: "連結リストの方が常に高速だと考える",
    distractor_rationales: ["不正解。途中挿入は要素の移動が必要。", "正解。インデックス指定で直接アクセス。", "不正解。ポインタ分のオーバーヘッドは連結リスト側。", "不正解。配列はサイズ固定のことが多い。"],
    basic_terms: "配列：連続領域の要素列、連結リスト：ポインタでつながったノード列"
  }),
  // L300 ×5
  q({
    domain: "情報・計算機科学",
    subdomain: "プログラミング",
    difficulty_initial: 300,
    cognitive_type: "用語・定義",
    question_text: "オブジェクト指向プログラミングにおいて、既存のクラスの性質を引き継いで新しいクラスを定義する仕組みはどれか。",
    choices: ["カプセル化", "継承", "ポリモーフィズム", "例外処理"],
    correct_choice_index: 1,
    short_explanation: "継承は親クラスの属性・メソッドを子クラスが受け継ぐ。",
    detailed_explanation: "カプセル化は内部実装の隠蔽、ポリモーフィズムは同一インタフェースでの多態性、例外処理はエラー制御。",
    learning_objective: "オブジェクト指向の三大概念を区別できる",
    common_misconception: "継承とポリモーフィズムを混同する",
    distractor_rationales: ["不正解。データと操作の隠蔽。", "正解。親子クラス間の性質の引継ぎ。", "不正解。同じ操作の異なる振る舞い。", "不正解。実行時エラーの処理。"],
    basic_terms: "継承：クラス間の性質の引継ぎ、カプセル化：内部の隠蔽"
  }),
  q({
    domain: "情報・計算機科学",
    subdomain: "ネットワーク",
    difficulty_initial: 300,
    cognitive_type: "比較・分類",
    question_text: "Web ブラウザと Web サーバ間で HTML ページを取得する際に用いられるプロトコルはどれか。",
    choices: ["FTP", "HTTP", "SMTP", "SNMP"],
    correct_choice_index: 1,
    short_explanation: "HTTP（HyperText Transfer Protocol）は Web の基盤プロトコル。",
    detailed_explanation: "FTP はファイル転送、SMTP はメール送信、SNMP はネットワーク管理用。",
    learning_objective: "主要インターネットプロトコルの用途を区別できる",
    common_misconception: "Web 通信は FTP で行われると誤解する",
    distractor_rationales: ["不正解。ファイル転送用。", "正解。Web ページ取得のプロトコル。", "不正解。メール送信用。", "不正解。ネットワーク管理用。"],
    basic_terms: "HTTP：Web 通信プロトコル、プロトコル：通信の約束事"
  }),
  q({
    domain: "情報・計算機科学",
    subdomain: "セキュリティ",
    difficulty_initial: 300,
    cognitive_type: "基本的な適用",
    question_text: "ユーザーを騙して不正なサイトへ誘導し、個人情報を窃取する攻撃手法として最も適切なものはどれか。",
    choices: ["フィッシング", "DDoS 攻撃", "ブルートフォース", "バッファオーバーフロー"],
    correct_choice_index: 0,
    short_explanation: "フィッシングは偽のメールやサイトで認証情報を騙し取る。",
    detailed_explanation: "DDoS はサービス妨害、ブルートフォースは総当たり攻撃、バッファオーバーフローはメモリ破壊の脆弱性悪用。",
    learning_objective: "代表的なサイバー攻撃の種類を識別できる",
    common_misconception: "すべての攻撃をウイルスと呼ぶ",
    distractor_rationales: ["正解。偽サイトによる情報窃取。", "不正解。大量アクセスによる妨害。", "不正解。パスワードの総当たり。", "不正解。プログラムの脆弱性悪用。"],
    basic_terms: "フィッシング：偽装による情報窃取、DDoS：分散サービス妨害攻撃"
  }),
  q({
    domain: "情報・計算機科学",
    subdomain: "OS",
    difficulty_initial: 300,
    cognitive_type: "原理・因果",
    question_text: "OS において、実行中のプログラムの実体を何というか。",
    choices: ["スレッド", "プロセス", "セマフォ", "デバイスドライバ"],
    correct_choice_index: 1,
    short_explanation: "プロセスはプログラムの実行単位であり、独立したメモリ空間を持つ。",
    detailed_explanation: "スレッドはプロセス内の実行単位。セマフォは同期プリミティブ、デバイスドライバはハードウェア制御。",
    learning_objective: "プロセスとスレッドの基本概念を説明できる",
    common_misconception: "プロセスとスレッドを同一視する",
    distractor_rationales: ["不正解。プロセス内の軽量実行単位。", "正解。プログラムの実行インスタンス。", "不正解。同期のためのカウンタ。", "不正解。ハードウェア制御ソフト。"],
    basic_terms: "プロセス：プログラムの実行単位、スレッド：プロセス内の実行フロー"
  }),
  q({
    domain: "情報・計算機科学",
    subdomain: "AI",
    difficulty_initial: 300,
    cognitive_type: "比較・分類",
    question_text: "正解ラベルのないデータから構造やパターンを見つける機械学習の方式はどれか。",
    choices: ["教師あり学習", "教師なし学習", "強化学習", "転移学習"],
    correct_choice_index: 1,
    short_explanation: "教師なし学習はクラスタリング等、ラベルなしデータの構造発見に用いる。",
    detailed_explanation: "教師あり学習はラベル付きデータ、強化学習は報酬最大化、転移学習は学習済み知識の再利用。",
    learning_objective: "機械学習の主要パラダイムを区別できる",
    common_misconception: "すべての学習が教師ありだと考える",
    distractor_rationales: ["不正解。正解ラベル付きデータを用いる。", "正解。ラベルなしデータのパターン発見。", "不正解。試行錯誤による方策学習。", "不正解。既存モデルの知識再利用。"],
    basic_terms: "教師なし学習：ラベルなしデータの学習、クラスタリング：グループ分け"
  }),
  // L400 ×1
  q({
    domain: "情報・計算機科学",
    subdomain: "アルゴリズム",
    difficulty_initial: 400,
    cognitive_type: "基本的な適用",
    question_text: "マージソートの計算量（要素数 n に対するオーダー）として正しいものはどれか。",
    choices: ["O(n)", "O(n log n)", "O(n²)", "O(2^n)"],
    correct_choice_index: 1,
    short_explanation: "マージソートは分割統治法により最悪・平均 O(n log n)。",
    detailed_explanation: "分割とマージを繰り返し、各段階で O(n) のマージを log n 回行う。",
    learning_objective: "代表的ソートアルゴリズムの計算量を説明できる",
    common_misconception: "効率的なソートはすべて O(n) だと誤解する",
    distractor_rationales: ["不正解。線形時間のソートは条件付き。", "正解。マージソートの漸近計算量。", "不正解。バブルソート等の計算量。", "不正解。指数時間。"],
    basic_terms: "マージソート：分割統治法によるソート、O(n log n)：準線形時間"
  }),
  // L500 ×2
  q({
    domain: "情報・計算機科学",
    subdomain: "セキュリティ",
    difficulty_initial: 500,
    cognitive_type: "基本的な適用",
    question_text: "Web アプリケーションのクロスサイトスクリプティング（XSS）攻撃を防ぐ基本対策として最も適切なものはどれか。",
    choices: ["ユーザー入力をそのまま HTML に埋め込む", "出力時にエスケープ処理を行う", "パスワードを平文で保存する", "HTTP のみを使用する"],
    correct_choice_index: 1,
    short_explanation: "出力エスケープにより悪意あるスクリプトの実行を防ぐ。",
    detailed_explanation: "XSS は入力データにスクリプトを混入させる攻撃。エスケープ・CSP・入力検証が対策。",
    learning_objective: "XSS 攻撃と防御策を説明できる",
    common_misconception: "XSS は SQL インジェクションと同一だと考える",
    distractor_rationales: ["不正解。スクリプト注入を許す。", "正解。出力エスケープで無害化。", "不正解。セキュリティを損なう。", "不正解。HTTPS が XSS 対策ではない。"],
    basic_terms: "XSS：悪意あるスクリプト注入、エスケープ：特殊文字の無害化"
  }),
  q({
    domain: "情報・計算機科学",
    subdomain: "OS",
    difficulty_initial: 500,
    cognitive_type: "原理・因果",
    question_text: "OS におけるデッドロックが発生する4つの必要条件のうち、資源を占有したまま他の資源を待つ条件はどれか。",
    choices: ["相互排除", "保持と待機", "非搶奪", "循環待機"],
    correct_choice_index: 1,
    short_explanation: "保持と待機（hold and wait）は資源保持中に追加資源を待つ状態。",
    detailed_explanation: "相互排除は資源の排他使用、非搶奪は資源の強制解放不可、循環待機はプロセス間の環状待ち。",
    learning_objective: "デッドロックの4条件を説明できる",
    common_misconception: "デッドロックは1つの条件だけで発生すると考える",
    distractor_rationales: ["不正解。資源の排他使用条件。", "正解。保持中に追加資源を待つ。", "不正解。資源の強制解放不可。", "不正解。プロセス間の環状待ち。"],
    basic_terms: "デッドロック：資源待ちの永久ブロック、相互排除：資源の排他使用"
  }),
  // L600 ×3
  q({
    domain: "情報・計算機科学",
    subdomain: "アルゴリズム",
    difficulty_initial: 600,
    cognitive_type: "基本的な適用",
    question_text: "非負の重みを持つグラフで、単一始点から全頂点への最短距離を求めるダイクストラ法の前提として正しいものはどれか。",
    choices: ["辺の重みに負の値があってもよい", "辺の重みは非負である", "グラフは非連結でなければならない", "全頂点の次数は偶数である"],
    correct_choice_index: 1,
    short_explanation: "ダイクストラ法は非負重みグラフに適用でき、負の辺にはベルマン・フォード法を用いる。",
    detailed_explanation: "貪欲に最短距離確定頂点を拡張。負の辺があると確定頂点の距離が後から更新されうる。",
    learning_objective: "ダイクストラ法の適用条件を説明できる",
    common_misconception: "最短経路アルゴリズムはすべての重みに適用できる",
    distractor_rationales: ["不正解。負の辺があると破綻する。", "正解。非負重みが前提。", "不正解。連結性の制約はない。", "不正解。次数の制約はない。"],
    basic_terms: "ダイクストラ法：単一始点最短経路、貪欲法：局所最適の繰り返し"
  }),
  q({
    domain: "情報・計算機科学",
    subdomain: "データ構造",
    difficulty_initial: 600,
    cognitive_type: "原理・因果",
    question_text: "赤黒木（Red-Black Tree）が平衡二分探索木として機能する主な性質はどれか。",
    choices: ["全ノードが赤色である", "根から葉までの黒ノード数がほぼ一定", "高さが常に 1 である", "左子のみを持つ"],
    correct_choice_index: 1,
    short_explanation: "赤黒木は黒高さ（black-height）の均衡により高さを O(log n) に抑える。",
    detailed_explanation: "赤黒性質（根は黒、赤の子は黒、経路上の黒ノード数一定）により最悪高さ ≤ 2 log(n+1)。",
    learning_objective: "赤黒木の平衡性の仕組みを説明できる",
    common_misconception: "二分木は挿入順に依存せず常に平衡だと誤解する",
    distractor_rationales: ["不正解。赤黒交互が規則。", "正解。黒高さの均衡が高さ制御の鍵。", "不正解。要素数に応じて高さは増える。", "不正解。二分探索木の定義に反する。"],
    basic_terms: "赤黒木：平衡二分探索木、黒高さ：根から葉までの黒ノード数"
  }),
  q({
    domain: "情報・計算機科学",
    subdomain: "ネットワーク",
    difficulty_initial: 600,
    cognitive_type: "用語・定義",
    question_text: "インターネットの自律システム（AS）間で経路情報を交換するプロトコルはどれか。",
    choices: ["OSPF", "BGP", "ARP", "DHCP"],
    correct_choice_index: 1,
    short_explanation: "BGP（Border Gateway Protocol）は AS 間の経路交換に用いられる。",
    detailed_explanation: "OSPF は AS 内のリンク状態ルーティング、ARP は IP-MAC 解決、DHCP は IP 割当。",
    learning_objective: "インターネットルーティングプロトコルの役割を区別できる",
    common_misconception: "OSPF がインターネット全体の経路を決めると誤解する",
    distractor_rationales: ["不正解。AS 内の IGP。", "正解。AS 間の EGP。", "不正解。アドレス解決。", "不正解。動的 IP 割当。"],
    basic_terms: "BGP：ボーダーゲートウェイプロトコル、AS：自律システム"
  }),
  // L700 ×2
  q({
    domain: "情報・計算機科学",
    subdomain: "OS",
    difficulty_initial: 700,
    cognitive_type: "原理・因果",
    question_text: "共有資源への排他的アクセスを実現する同期プリミティブとして、カウンタ値に基づき複数プロセスの入場を制御できるものはどれか。",
    choices: ["ミューテックス", "セマフォ", "スピンロック", "条件変数のみ"],
    correct_choice_index: 1,
    short_explanation: "セマフォはカウンタで資源数を管理し、複数の同時アクセスを制御できる。",
    detailed_explanation: "バイナリセマフォはミューテックス相当。カウントセマフォはプール資源の管理に用いる。",
    learning_objective: "セマフォとミューテックスの違いを説明できる",
    common_misconception: "セマフォとミューテックスは完全に同一だと考える",
    distractor_rationales: ["不正解。基本的に1つの排他ロック。", "正解。カウンタによる入場制御。", "不正解。ビジーウェイトによるロック。", "不正解。待機条件の通知に用いる。"],
    basic_terms: "セマフォ：カウンタ型同期プリミティブ、ミューテックス：相互排除ロック"
  }),
  q({
    domain: "情報・計算機科学",
    subdomain: "暗号",
    difficulty_initial: 700,
    cognitive_type: "誤解・境界",
    question_text: "RSA 暗号の安全性が依存する数学的困難性として最も適切なものはどれか。",
    choices: ["離散対数問題", "大きな合成数の素因数分解", "巡回セールスマン問題", "最大流問題"],
    correct_choice_index: 1,
    short_explanation: "RSA は大きな合成数 n = pq の素因数分解の困難性に基づく。",
    detailed_explanation: "離散対数は DH や ElGamal の基盤。RSA の秘密鍵復元は n の因数分解に帰着する。",
    learning_objective: "公開鍵暗号の安全性基盤を説明できる",
    common_misconception: "RSA と DH が同じ数学問題に基づくと誤解する",
    distractor_rationales: ["不正解。DH 等の基盤。", "正解。RSA の安全性基盤。", "不正解。NP 困難だが暗号の標準基盤ではない。", "不正解。グラフ上の最適化問題。"],
    basic_terms: "RSA：素因数分解困難性に基づく公開鍵暗号、離散対数：別の暗号基盤"
  })
];
