import { q } from "../lib/batch50-helpers.mjs";

export const biologyGap = [
  q({ domain: "生物", subdomain: "細胞", difficulty_initial: 100, cognitive_type: "用語・定義",
    question_text: "植物細胞にあって動物細胞にない構造として正しいものはどれか。",
    choices: ["細胞膜", "細胞壁", "核", "ミトコンドリア"], correct_choice_index: 1,
    short_explanation: "細胞壁は植物細胞・菌類などに特有。動物細胞にはない。",
    detailed_explanation: "植物細胞はセルロース性細胞壁を持つ。動物細胞は細胞膜のみで囲まれる。",
    learning_objective: "植物細胞と動物細胞の構造差を説明できる", common_misconception: "すべての細胞に細胞壁があると考える",
    distractor_rationales: ["不正解。両方にある。", "正解。植物細胞特有。", "不正解。真核細胞共通。", "不正解。両方にある。"],
    basic_terms: "細胞壁：細胞外側の支持構造、細胞膜：細胞の境界膜" }),
  q({ domain: "生物", subdomain: "分類", difficulty_initial: 200, cognitive_type: "比較・分類",
    question_text: "生物の分類において、哺乳類に共通する特徴として正しいものはどれか。",
    choices: ["卵生のみ", "乳腺で幼児を育てる", "えら呼吸", "変温動物"],
    correct_choice_index: 1, short_explanation: "哺乳類は乳腺で乳を分泌し幼児を育てる。",
    detailed_explanation: "哺乳類は恒温・肺呼吸・乳腺・毛髪などが特徴。",
    learning_objective: "哺乳類の主要特徴を説明できる", common_misconception: "哺乳類がすべて胎生だと限定しすぎる",
    distractor_rationales: ["不正解。卵生哺乳類もいる。", "正解。哺乳類の定義的特徴。", "不正解。肺呼吸。", "不正解。恒温動物。"],
    basic_terms: "哺乳類：乳腺を持つ脊椎動物、恒温動物：体温を一定に保つ" }),
  q({ domain: "生物", subdomain: "生態", difficulty_initial: 200, cognitive_type: "原理・因果",
    question_text: "食物連鎖において、植物が担う栄養段階として正しいものはどれか。",
    choices: ["一次消費者", "生産者", "分解者", "二次消費者"],
    correct_choice_index: 1, short_explanation: "植物は光合成で有機物を作る生産者。",
    detailed_explanation: "生産者→一次消費者→二次消費者…の流れ。植物は生産者。",
    learning_objective: "食物連鎖の栄養段階を区別できる", common_misconception: "植物を消費者と誤分類する",
    distractor_rationales: ["不正解。草食動物が一次消費者。", "正解。光合成による生産者。", "不正解。細菌・菌類など。", "不正解。肉食動物の段階。"],
    basic_terms: "生産者：有機物を作る生物、食物連鎖：栄養関係の系列" }),
  q({ domain: "生物", subdomain: "人体", difficulty_initial: 200, cognitive_type: "基本的な適用",
    question_text: "人体で血液を全身に送り出す役割を主に担う器官はどれか。",
    choices: ["肺", "心臓", "肝臓", "腎臓"], correct_choice_index: 1,
    short_explanation: "心臓は筋肉質のポンプとして血液を循環させる。",
    detailed_explanation: "右心系・左心系が体循環・肺循環を担う。",
    learning_objective: "循環器系の主要器官を説明できる", common_misconception: "肺が血液を送ると誤解する",
    distractor_rationales: ["不正解。ガス交換。", "正解。血液ポンプ。", "不正解。代謝・解毒。", "不正解。ろ過・排泄。"],
    basic_terms: "心臓：血液を送り出す筋肉器官、循環：血液の体内循環" }),
  q({ domain: "生物", subdomain: "遺伝", difficulty_initial: 300, cognitive_type: "原理・因果",
    question_text: "メンデルの法則において、対立遺伝子が分離して配子に入る法則はどれか。",
    choices: ["優性の法則", "分離の法則", "独立の法則", "連鎖の法則"],
    correct_choice_index: 1, short_explanation: "分離の法則：対立遺伝子が減数分裂で分かれる。",
    detailed_explanation: "メンデル第一法則（分離）。配子には対立遺伝子のいずれか1つ。",
    learning_objective: "メンデルの分離の法則を説明できる", common_misconception: "独立の法則と混同する",
    distractor_rationales: ["不正解。優性の表現型。", "正解。分離の法則。", "不正解。異なる遺伝子座。", "不正解。染色体連鎖。"],
    basic_terms: "対立遺伝子：同じ遺伝子座の異なる形、分離の法則：配子への分配" }),
  q({ domain: "生物", subdomain: "細胞生物学", difficulty_initial: 300, cognitive_type: "用語・定義",
    question_text: "細胞内でタンパク質合成を行う細胞小器官はどれか。",
    choices: ["リボソーム", "リソソーム", "中心体", "液胞"],
    correct_choice_index: 0, short_explanation: "リボソームが mRNA を読み取りアミノ酸を結合する。",
    detailed_explanation: "リボソームは細胞質・粗面小胞体に存在。翻訳の場。",
    learning_objective: "タンパク質合成の場所を説明できる", common_misconception: "核でタンパク質が合成されると誤解する",
    distractor_rationales: ["正解。翻訳の場。", "不正解。加水分解小器官。", "不正解。分裂に関与。", "不正解。植物の貯蔵。"],
    basic_terms: "リボソーム：タンパク質合成装置、翻訳：mRNA からタンパク質を作る" }),
  q({ domain: "生物", subdomain: "生化学", difficulty_initial: 300, cognitive_type: "基本的な適用",
    question_text: "グルコースが解糖系で最初に生成するエネルギー通貨分子として正しいものはどれか。",
    choices: ["ATP", "NADH", "FADH₂", "GTP のみ"],
    correct_choice_index: 0, short_explanation: "解糖系では基質レベルリン酸化で ATP が生成される。",
    detailed_explanation: "解糖 1分子でネット ATP 2。ATP は直接エネルギー通貨。",
    learning_objective: "解糖系の産物を説明できる", common_misconception: "解糖で NADH だけがエネルギー通貨だと考える",
    distractor_rationales: ["正解。直接のエネルギー通貨。", "不正解。還元力キャリア。", "不正解。電子伝達系で利用。", "不正解。ATP が主。"],
    basic_terms: "解糖系：グルコースをピルビン酸に分解、ATP：エネルギー通貨" }),
  q({ domain: "生物", subdomain: "免疫", difficulty_initial: 300, cognitive_type: "比較・分類",
    question_text: "獲得免疫の特徴として正しいものはどれか。",
    choices: ["生まれつき備わり同じ反応速度", "抗原特異的で記憶を形成する", "皮膚のバリアのみ", "補体の常時活性"],
    correct_choice_index: 1, short_explanation: "獲得免疫は抗原特異的かつ免疫記憶を持つ。",
    detailed_explanation: "B細胞・T細胞が関与。初免疫と再免疫で応答が異なる。",
    learning_objective: "自然免疫と獲得免疫を区別できる", common_misconception: "すべての免疫が非特異的だと考える",
    distractor_rationales: ["不正解。自然免疫の特徴。", "正解。獲得免疫の特徴。", "不正解。自然免疫のバリア。", "不正解。自然免疫の成分。"],
    basic_terms: "獲得免疫：抗原特異的な後天的免疫、免疫記憶：再感染時の迅速応答" }),
  q({ domain: "生物", subdomain: "進化", difficulty_initial: 300, cognitive_type: "誤解・境界",
    question_text: "自然選択の必要条件として正しい組合せはどれか。",
    choices: ["遺伝的変異・生殖における差異・遺伝可能性", "個体の意図的適応・ラマルク遺伝", "環境の意図・突然変異のみ", "完全なランダム淘汰"],
    correct_choice_index: 0, short_explanation: "変異・差異・遺伝性が自然選択の前提。",
    detailed_explanation: "ダーウィンの自然選択：変異が存在し、生存・生殖差があり、遺伝する性状が頻度変化。",
    learning_objective: "自然選択の条件を説明できる", common_misconception: "個体が意図的に適応すると考える",
    distractor_rationales: ["正解。自然選択の三要素。", "不正解。ラマルク説。", "不正解。環境の意図はない。", "不正解。完全ランダムではない。"],
    basic_terms: "自然選択：環境に適した個体が残る過程、遺伝的変異：個体間の遺伝的差異" }),
  q({ domain: "生物", subdomain: "分子生物学", difficulty_initial: 400, cognitive_type: "原理・因果",
    question_text: "DNA 複製が半保存的であることの意味として正しいものはどれか。",
    choices: ["両鎖がともに新規合成される", "各子DNAに親鎖1本と新鎖1本が含まれる", "複製は一度だけ行われる", "RNA がテンプレートになる"],
    correct_choice_index: 1, short_explanation: "メセルソン・スタール実験が示した半保存複製。",
    detailed_explanation: "親DNAの各鎖がテンプレートとなり、子DNAは旧鎖+新鎖。",
    learning_objective: "半保存複製を説明できる", common_misconception: "全鎖が新規合成だと考える",
    distractor_rationales: ["不正解。全保存ではない。", "正解。半保存の定義。", "不正解。細胞分裂ごとに複製。", "不正解。DNA 複製のテンプレートは DNA。"],
    basic_terms: "半保存複製：親鎖を保ちつつ複製、テンプレート：新鎖合成の型" }),
  q({ domain: "生物", subdomain: "遺伝学", difficulty_initial: 400, cognitive_type: "基本的な適用",
    question_text: "ヒトの体細胞の染色体数として正しいものはどれか。",
    choices: ["23本", "46本", "92本", "22本"],
    correct_choice_index: 1, short_explanation: "体細胞は二倍体 2n = 46 本（23 対）。",
    detailed_explanation: "生殖細胞は n = 23。受精で 2n = 46 に回復。",
    learning_objective: "体細胞と生殖細胞の染色体数を区別できる", common_misconception: "23 本を体細胞と誤る",
    distractor_rationales: ["不正解。生殖細胞の n。", "正解。2n = 46。", "不正解。4n ではない。", "不正解。常染色体対数と混同。"],
    basic_terms: "二倍体：2セットの染色体、染色体対：相同染色体のペア" }),
  q({ domain: "生物", subdomain: "生化学", difficulty_initial: 400, cognitive_type: "比較・分類",
    question_text: "酵素の基質特異性の主な原因として最も適切なものはどれか。",
    choices: ["分子量が同じから", "活性部位の立体構造が特定基質に適合するから", "すべての酵素が同じ pH で最適だから", "補酵素が不要だから"],
    correct_choice_index: 1, short_explanation: "ロックとキー/誘導適合モデルで活性部位が基質を認識。",
    detailed_explanation: "活性部位のアミノ酸配列・立体構造が基質特異性を決める。",
    learning_objective: "酵素の基質特異性を説明できる", common_misconception: "酵素がすべての反応を触媒すると考える",
    distractor_rationales: ["不正解。分子量は無関係。", "正解。活性部位の構造。", "不正解。pH 最適は酵素ごとに異なる。", "不正解。多くの酵素は補酵素を要する。"],
    basic_terms: "活性部位：触媒反応の場、基質特異性：特定基質に反応する性質" }),
  q({ domain: "生物", subdomain: "細胞生物学", difficulty_initial: 400, cognitive_type: "用語・定義",
    question_text: "細胞周期の M 期に起こる主な出来事として正しいものはどれか。",
    choices: ["DNA 複製", "有糸分裂・細胞質分裂", "G₁ 期の成長のみ", "減数分裂の前期Iのみ"],
    correct_choice_index: 1, short_explanation: "M 期は分裂期で有糸分裂と cytokinesis。",
    detailed_explanation: "間期（G₁-S-G₂）で準備、M 期で染色体分離と細胞分裂。",
    learning_objective: "細胞周期の各期の出来事を説明できる", common_misconception: "DNA 複製が M 期だと誤解する",
    distractor_rationales: ["不正解。S 期。", "正解。M 期の分裂。", "不正解。G₁ は間期。", "不正解。減数分裂は別過程。"],
    basic_terms: "M 期：分裂期、有糸分裂：核分裂" }),
  q({ domain: "生物", subdomain: "生態", difficulty_initial: 400, cognitive_type: "誤解・境界",
    question_text: "生態系におけるエネルギー流の特徴として正しいものはどれか。",
    choices: ["エネルギーは100%次段階に伝わる", "各栄養段階で大部分が熱として散逸する", "物質と同様に生態系内で増える", "分解者はエネルギーを生産する"],
    correct_choice_index: 1, short_explanation: "エネルギーは一方向に流れ各段階で熱損失。",
    detailed_explanation: "10% 法則など。エネルギーは循環せず物質は循環。",
    learning_objective: "エネルギー流と物質循環の違いを説明できる", common_misconception: "エネルギーが物質のように循環すると考える",
    distractor_rationales: ["不正解。大部分が損失。", "正解。熱散逸が特徴。", "不正解。エネルギーは保存だが利用可能量は減る。", "不正解。分解者は有機物を無機化。"],
    basic_terms: "栄養段階：食物連鎖の階層、エネルギー効率：次段階への伝達率" }),
  q({ domain: "生物", subdomain: "分子生物学", difficulty_initial: 500, cognitive_type: "原理・因果",
    question_text: "転写において RNA ポリメラーゼが結合する DNA 上の配列として最も適切なものはどれか。",
    choices: ["オリジン", "プロモーター", "テロメア", "エンハンサーのみ"],
    correct_choice_index: 1, short_explanation: "プロモーターは転写開始部位近傍の認識配列。",
    detailed_explanation: "RNA ポリメラーゼはプロモーターに結合し転写開始。",
    learning_objective: "転写調節の基本配列を説明できる", common_misconception: "複製起点と転写起点を混同する",
    distractor_rationales: ["不正解。DNA 複製起点。", "正解。転写開始認識。", "不正解。染色体末端。", "不正解。エンハンサーは調節だが結合は複合的。"],
    basic_terms: "プロモーター：転写開始を決める配列、転写：DNA から RNA 合成" }),
  q({ domain: "生物", subdomain: "生化学", difficulty_initial: 500, cognitive_type: "基本的な適用",
    question_text: "クエン酸回路（TCA 回路）がミトコンドリア基質で行われる主な理由として最も適切なものはどれか。",
    choices: ["核内に酵素があるから", "ミトコンドリアに回路酵素が局在し NADH/FADH₂ を電子伝達系に供給するから", "細胞膜で行われるから", "リボソームと結合するから"],
    correct_choice_index: 1, short_explanation: "TCA 回路酵素はミトコンドリアマトリックスに局在。",
    detailed_explanation: "TCA はミトコンドリアで CO₂ と還元力を生成し呼吸鎖へ。",
    learning_objective: "細胞内代謝の区画化を説明できる", common_misconception: "TCA が細胞質で完結すると考える",
    distractor_rationales: ["不正解。核は DNA 転写。", "正解。ミトコンドリア基質での代謝。", "不正解。膜透過はあるが主反応はマトリックス。", "不正解。タンパク質合成とは無関係。"],
    basic_terms: "クエン酸回路：好気的代謝の中心経路、電子伝達系：酸化的リン酸化" }),
  q({ domain: "生物", subdomain: "遺伝学", difficulty_initial: 500, cognitive_type: "比較・分類",
    question_text: "連鎖遺伝の特徴として正しいものはどれか（X 連鎖遺伝を想定）。",
    choices: ["男女に同じ頻度で現れる", "男性で表現型が出やすい", "常染色体のみに存在", "環境だけで決まる"],
    correct_choice_index: 1, short_explanation: "X 連鎖劣性は男性（ hemizygous ）で発症しやすい。",
    detailed_explanation: "男性は X が1本のため劣性でも発現。色覚異常など。",
    learning_objective: "性連鎖遺伝の表現型頻度を説明できる", common_misconception: "連鎖遺伝を常染色体遺伝と混同する",
    distractor_rationales: ["不正解。男性に多い。", "正解。X 連鎖劣性の特徴。", "不正解。X または Y にある。", "不正解。遺伝的要因が主。"],
    basic_terms: "性連鎖：性染色体上の遺伝子、ヘミ接合：男性の X 1 本状態" }),
  q({ domain: "生物", subdomain: "免疫学", difficulty_initial: 600, cognitive_type: "原理・因果",
    question_text: "抗体の基本構造として正しいものはどれか。",
    choices: ["1 つの重鎖のみ", "2 つの重鎖と 2 つの軽鎖", "4 つの軽鎖のみ", "RNA とタンパク質の複合体"],
    correct_choice_index: 1, short_explanation: "IgG などは H2L2 の4鎖構造。",
    detailed_explanation: "抗体は重鎖2・軽鎖2。Fab で抗原結合、Fc で効果機能。",
    learning_objective: "抗体の構造を説明できる", common_misconception: "抗体が単一ポリペプチドだと考える",
    distractor_rationales: ["不正解。軽鎖も必要。", "正解。標準的4鎖構造。", "不正解。重鎖が必要。", "不正解。タンパク質性。"],
    basic_terms: "抗体：免疫グロブリン、重鎖・軽鎖：抗体のサブユニット" }),
  q({ domain: "生物", subdomain: "分子生物学", difficulty_initial: 600, cognitive_type: "用語・定義",
    question_text: "mRNA のコドン UAG の意味として正しいものはどれか。",
    choices: ["メチオニン", "セリン", "終止コドン", "開始コドンのみ"],
    correct_choice_index: 2, short_explanation: "UAG は終止コドン（アンバー）。",
    detailed_explanation: "終止コドン UAA, UAG, UGA。AUG が開始コドン。",
    learning_objective: "遺伝暗号の開始・終止コドンを区別できる", common_misconception: "すべてのコドンがアミノ酸をコードすると考える",
    distractor_rationales: ["不正解。AUG がメチオニン。", "不正解。UCU などがセリン。", "正解。終止コドン。", "不正解。開始は AUG。"],
    basic_terms: "コドン：3塩基のアミノ酸コード、終止コドン：翻訳終了信号" }),
  q({ domain: "生物", subdomain: "細胞生物学", difficulty_initial: 600, cognitive_type: "誤解・境界",
    question_text: "細胞凋亡（アポトーシス）の特徴として正しいものはどれか。",
    choices: ["膜破綻による炎症を伴う壊死", "プログラムされた細胞死で細胞が縮小・断片化する", "すべての細胞死が同じ機構", "必ず病原菌感染による"],
    correct_choice_index: 1, short_explanation: "アポトーシスはカスパーゼ活性化による調節された死。",
    detailed_explanation: "アポトーシスは発生・免疫・がん抑制で重要。壊死とは異なる。",
    learning_objective: "アポトーシスと壊死を区別できる", common_misconception: "すべての細胞死を壊死と考える",
    distractor_rationales: ["不正解。壊死の特徴。", "正解。アポトーシスの特徴。", "不正解。機構は異なる。", "不正解。生理的にも起こる。"],
    basic_terms: "アポトーシス：プログラム細胞死、カスパーゼ：アポトーシス酵素" }),
  q({ domain: "生物", subdomain: "遺伝学", difficulty_initial: 700, cognitive_type: "基本的な適用",
    question_text: "制限酵素による DNA 断片化が遺伝子組換えで重要な理由として最も適切なものはどれか。",
    choices: ["DNA をランダムに複製するから", "特異配列で切断し相同末端や適合末端を作るから", "タンパク質を切断するから", "RNA を除去するから"],
    correct_choice_index: 1, short_explanation: "制限酵素は認識配列で切断しクビリを作る。",
    detailed_explanation: "EcoRI などでベクターと挿入片を同じクビリで接合。",
    learning_objective: "制限酵素の役割を説明できる", common_misconception: "制限酵素が複製を行うと誤解する",
    distractor_rationales: ["不正解。切断が主目的。", "正解。特異切断とクビリ形成。", "不正解。プロテアーゼの役割。", "不正解。RNase の役割。"],
    basic_terms: "制限酵素：特異配列を認識するヌクレアーゼ、クビリ：切断末端" }),
  q({ domain: "生物", subdomain: "分子生物学", difficulty_initial: 700, cognitive_type: "原理・因果",
    question_text: "ラクトースオペロンにおいて lactose 存在下で転写が誘導される主な機構として正しいものはどれか。",
    choices: ["リプレッサーがオペレーターに結合強化", "アラクトースがリプレッサーを不活性化しオペレーターから解離", "CAP が常に阻害", "RNA ポリメラーゼが分解される"],
    correct_choice_index: 1, short_explanation: "アラクトース（アロラクトース）がリプレッサーを外し転写開始。",
    detailed_explanation: "ラクトース存在→リプレッサー解離+CAP-cAMP で転写誘導。",
    learning_objective: "オペロン調節の負の制御を説明できる", common_misconception: "リプレッサーが誘導時に結合すると誤解する",
    distractor_rationales: ["不正解。誘導時は結合弱まる。", "正解。リプレッサー不活性化。", "不正解。CAP は正の制御。", "不正解。酵素は分解しない。"],
    basic_terms: "オペロン：原核の遺伝子群調節、リプレッサー：転写阻害タンパク質" }),
  q({ domain: "生物", subdomain: "神経科学", difficulty_initial: 700, cognitive_type: "比較・分類",
    question_text: "シナプス後膜での興奮性伝達の例として正しいものはどれか。",
    choices: ["GABA 受容体活性化", "グルタミン酸による脱分極", "グリシンによる Cl⁻ 流入", "K⁺ チャネル開放のみ"],
    correct_choice_index: 1, short_explanation: "グルタミン酸は主要興奮性神経伝達物質。",
    detailed_explanation: "グルタミン酸→AMPA/NMDA で Na⁺ 流入・脱分極。GABA/グリシンは抑制性。",
    learning_objective: "興奮性と抑制性シナプスを区別できる", common_misconception: "すべての神経伝達が興奮性だと考える",
    distractor_rationales: ["不正解。抑制性。", "正解。興奮性伝達。", "不正解。抑制性。", "不正解。K⁺ 流出で抑制。"],
    basic_terms: "興奮性シナプス：脱分極を起こす、グルタミン酸：主要興奮性伝達物質" })
];
